# WARNING: THIS FILE HAS BEEN GENERATED!
# Modifications to this file will not be kept.
# If you need to change something here, check out codegen.py and the templates directory.


import typing

from .items import items_dict
from .types.items import ItemData, ItemPoolEntry
from .types.condition import *

item_pools_template: dict[str, list[ItemPoolEntry]] = {
    "Required": [
        ItemPoolEntry(item=items_dict['Heat', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Cold', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Shock', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Wave', 1], quantity=1),
        ItemPoolEntry(item=items_dict['SP Upgrade', 1], quantity=2),
        ItemPoolEntry(item=items_dict['Disc of Flora', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Disc of Insight', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Cursed Coin', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Shiny Orb', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Mine Pass', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Guild Pass', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Maroon Cave Pass', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Pond Slums Pass', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Blue Ice Shade', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Meteor Shade', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Red Flame Shade', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Yellow Sand Shade', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Purple Bolt Shade', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Star Shade', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Azure Drop Shade', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Green Leaf Shade', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Green Seed Shade', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Mine Key', 1], quantity=5),
        ItemPoolEntry(item=items_dict["Faj'ro Key", 1], quantity=9),
        ItemPoolEntry(item=items_dict["Zir'vitar Key", 1], quantity=2),
        ItemPoolEntry(item=items_dict["So'najiz Key", 1], quantity=4),
        ItemPoolEntry(item=items_dict["Krys'kajo Key", 1], quantity=2),
        ItemPoolEntry(item=items_dict["Thief's Key", 1], quantity=1),
        ItemPoolEntry(item=items_dict['White Key', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Radiant Key', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Mine Master Key', 1], quantity=1),
        ItemPoolEntry(item=items_dict["Faj'ro Master Key", 1], quantity=1),
        ItemPoolEntry(item=items_dict['Kajo Master Key', 1], quantity=1),
        ItemPoolEntry(item=items_dict['East Gaia Pass', 1], quantity=1),
        ItemPoolEntry(item=items_dict['West Gaia Pass', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Old Dojo Key', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Broken Gauntlet', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Broken Shield', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Broken Chakrams', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Broken Sword', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Broken Deck', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Old Blueprint', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Very Large Ember', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Halcyon Droplet', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Portrait of Ruin', 1], quantity=1),
        ItemPoolEntry(item=items_dict["Heaven's Seed", 1], quantity=1),
        ItemPoolEntry(item=items_dict['Everlasting Amber', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Galaxy Berry', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Dream Globe', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Tremor Engine', 1], quantity=4),
        ItemPoolEntry(item=items_dict['Geta Wood', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Geta Glue', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Hungry Salmon', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Mysterious Box', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Omni Lock', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Golden Triangle', 1], quantity=3),
        ItemPoolEntry(item=items_dict["King's Ring", 1], quantity=1),
    ],
    "Common Consumables": [
        ItemPoolEntry(item=items_dict['Sandwich', 3], quantity=40),
        ItemPoolEntry(item=items_dict['Hi-Sandwich', 3], quantity=40),
        ItemPoolEntry(item=items_dict['Green Leaf Tea', 2], quantity=40),
        ItemPoolEntry(item=items_dict['Spicy Bun', 3], quantity=30),
        ItemPoolEntry(item=items_dict['Meaty Risotto', 1], quantity=30),
        ItemPoolEntry(item=items_dict['Fruit Salad', 3], quantity=25),
        ItemPoolEntry(item=items_dict['Veggie Wraps', 3], quantity=25),
    ],
    "Common Drops": [
        ItemPoolEntry(item=items_dict['Autumn Leaves', 4], quantity=15),
        ItemPoolEntry(item=items_dict['Gold Beetle', 4], quantity=15),
        ItemPoolEntry(item=items_dict['Feather Leaf', 5], quantity=17),
        ItemPoolEntry(item=items_dict['Pike Wood', 5], quantity=17),
        ItemPoolEntry(item=items_dict['Bergen Ice', 5], quantity=9),
        ItemPoolEntry(item=items_dict['Bug Shell', 5], quantity=13),
        ItemPoolEntry(item=items_dict['Tough Sand', 4], quantity=13),
        ItemPoolEntry(item=items_dict['Vivid Water', 5], quantity=20),
        ItemPoolEntry(item=items_dict['Crystal Leek', 4], quantity=15),
        ItemPoolEntry(item=items_dict['Old Bones', 4], quantity=12),
        ItemPoolEntry(item=items_dict['Parched Leaves', 4], quantity=13),
        ItemPoolEntry(item=items_dict['White Grain', 4], quantity=13),
        ItemPoolEntry(item=items_dict['Curly Fern', 4], quantity=11),
        ItemPoolEntry(item=items_dict['Common Planter', 4], quantity=11),
        ItemPoolEntry(item=items_dict['Blue Mango', 4], quantity=11),
        ItemPoolEntry(item=items_dict['Venom Shroom', 4], quantity=11),
        ItemPoolEntry(item=items_dict['Green Arbor', 4], quantity=9),
        ItemPoolEntry(item=items_dict['Blue Grass', 4], quantity=9),
        ItemPoolEntry(item=items_dict['Dirty Rubble', 4], quantity=9),
    ],
    "Rare Consumables": [
        ItemPoolEntry(item=items_dict['Chef Sandwich', 3], quantity=40),
        ItemPoolEntry(item=items_dict['Mega-Sandwich', 2], quantity=35),
        ItemPoolEntry(item=items_dict['Sweet Berry Tea', 2], quantity=40),
        ItemPoolEntry(item=items_dict['Flaming Bun', 3], quantity=30),
        ItemPoolEntry(item=items_dict['Steak, rare', 3], quantity=30),
        ItemPoolEntry(item=items_dict['Chili Con Carne', 2], quantity=30),
        ItemPoolEntry(item=items_dict['Shrimp Risotto', 1], quantity=20),
        ItemPoolEntry(item=items_dict['Fruit Pie', 3], quantity=15),
        ItemPoolEntry(item=items_dict['Ginger Tom. Salad', 3], quantity=10),
    ],
    "Rare Drops": [
        ItemPoolEntry(item=items_dict['Season Apples', 5], quantity=18),
        ItemPoolEntry(item=items_dict['Twilight Dew', 5], quantity=18),
        ItemPoolEntry(item=items_dict['Rusty Bits', 5], quantity=18),
        ItemPoolEntry(item=items_dict['Metal Gears', 3], quantity=15),
        ItemPoolEntry(item=items_dict['Purple Ore Lump', 6], quantity=21),
        ItemPoolEntry(item=items_dict['Arid Lumber', 4], quantity=17),
        ItemPoolEntry(item=items_dict['Cactone Fruit', 4], quantity=15),
        ItemPoolEntry(item=items_dict['Palmapple Seed', 3], quantity=16),
        ItemPoolEntry(item=items_dict['Glaring Rock', 4], quantity=16),
        ItemPoolEntry(item=items_dict['Helix Relic', 5], quantity=14),
        ItemPoolEntry(item=items_dict['Ripe Apples', 5], quantity=17),
        ItemPoolEntry(item=items_dict['Sunset Dew', 5], quantity=17),
        ItemPoolEntry(item=items_dict['Steel Comb', 4], quantity=16),
        ItemPoolEntry(item=items_dict['Spiky Nut', 4], quantity=18),
        ItemPoolEntry(item=items_dict['Exotic Resin', 3], quantity=15),
        ItemPoolEntry(item=items_dict['Glowing Sphere', 4], quantity=17),
        ItemPoolEntry(item=items_dict['Catalop Pellet', 4], quantity=13),
        ItemPoolEntry(item=items_dict['Pink Petal', 3], quantity=13),
        ItemPoolEntry(item=items_dict['Spark Tin', 3], quantity=11),
    ],
    "Epic Consumables": [
        ItemPoolEntry(item=items_dict['Cross Sandwich', 2], quantity=50),
        ItemPoolEntry(item=items_dict['Pepper Night Tea', 1], quantity=40),
        ItemPoolEntry(item=items_dict['Blazing Bun', 1], quantity=35),
        ItemPoolEntry(item=items_dict['Chili Dog', 1], quantity=30),
        ItemPoolEntry(item=items_dict['Gourmet Steak', 2], quantity=30),
        ItemPoolEntry(item=items_dict['Cold Platter', 2], quantity=25),
        ItemPoolEntry(item=items_dict['Green Risotto', 2], quantity=20),
        ItemPoolEntry(item=items_dict['Bear Beer', 3], quantity=20),
        ItemPoolEntry(item=items_dict['Crab Mead', 3], quantity=15),
        ItemPoolEntry(item=items_dict['Whale Wine', 3], quantity=15),
    ],
    "Epic Drops": [
        ItemPoolEntry(item=items_dict['Bear Cicada', 3], quantity=14),
        ItemPoolEntry(item=items_dict['Azure Dragonfly', 3], quantity=18),
        ItemPoolEntry(item=items_dict['Frozen Tear', 3], quantity=18),
        ItemPoolEntry(item=items_dict['Winter Thorn', 2], quantity=16),
        ItemPoolEntry(item=items_dict['Blue Orb', 2], quantity=14),
        ItemPoolEntry(item=items_dict['Rainbow Gem', 3], quantity=12),
        ItemPoolEntry(item=items_dict['Maroon Chestnut', 4], quantity=15),
        ItemPoolEntry(item=items_dict['Ancient Earth', 3], quantity=14),
        ItemPoolEntry(item=items_dict['Lucid Shard', 3], quantity=16),
        ItemPoolEntry(item=items_dict['Wolf Cicada', 4], quantity=15),
        ItemPoolEntry(item=items_dict['Crimson Dragonfly', 3], quantity=14),
        ItemPoolEntry(item=items_dict['Elder Wood', 3], quantity=18),
        ItemPoolEntry(item=items_dict['Royal Hive', 2], quantity=13),
        ItemPoolEntry(item=items_dict['Moon Fruit', 3], quantity=16),
        ItemPoolEntry(item=items_dict['Star Fruit', 2], quantity=16),
        ItemPoolEntry(item=items_dict['Virus Root', 2], quantity=16),
        ItemPoolEntry(item=items_dict['Steel Bamboo', 4], quantity=12),
        ItemPoolEntry(item=items_dict['Mystery Grape', 3], quantity=12),
        ItemPoolEntry(item=items_dict['Cobalt Crystal', 4], quantity=12),
    ],
    "Legendary Consumables": [
        ItemPoolEntry(item=items_dict['Final Dinner', 1], quantity=30),
        ItemPoolEntry(item=items_dict['Full Course', 1], quantity=30),
        ItemPoolEntry(item=items_dict['One Up', 1], quantity=30),
        ItemPoolEntry(item=items_dict['Rising Super Star', 1], quantity=25),
        ItemPoolEntry(item=items_dict['Guacamole Toast', 1], quantity=25),
        ItemPoolEntry(item=items_dict['Cheese Spaetzle', 1], quantity=20),
        ItemPoolEntry(item=items_dict['Spicy Beat-0-Type', 1], quantity=20),
        ItemPoolEntry(item=items_dict['Durian', 1], quantity=20),
        ItemPoolEntry(item=items_dict['Dk Pepper', 1], quantity=15),
        ItemPoolEntry(item=items_dict['Mooncake', 1], quantity=12),
    ],
    "Pets": [
        ItemPoolEntry(item=items_dict['Orange Twister', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Baby Peng', 1], quantity=1),
        ItemPoolEntry(item=items_dict['FDNI Fox', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Good Boy', 1], quantity=1),
        ItemPoolEntry(item=items_dict['S-Rex', 1], quantity=1),
        ItemPoolEntry(item=items_dict["Lil' Reap", 1], quantity=1),
        ItemPoolEntry(item=items_dict['Red Liz', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Shy Fly', 1], quantity=1),
        ItemPoolEntry(item=items_dict['T.A.N.K.', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Micro Crawler', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Cool Bar', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Batboy', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Butterfliege', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Piggybank', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Seedling', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Turbo', 1], quantity=1),
        ItemPoolEntry(item=items_dict['I Rob-0T', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Baby of the East', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Goose', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Nuclear Roach', 1], quantity=1),
        ItemPoolEntry(item=items_dict['Chunky', 1], quantity=1),
    ],
    
}

item_groups: dict[str, list[ItemData]] = {
    "Common Consumables": [
        items_dict['Sandwich', 3],
        items_dict['Hi-Sandwich', 3],
        items_dict['Green Leaf Tea', 2],
        items_dict['Spicy Bun', 3],
        items_dict['Meaty Risotto', 1],
        items_dict['Fruit Salad', 3],
        items_dict['Veggie Wraps', 3],
    ],
    "Common Drops": [
        items_dict['Autumn Leaves', 4],
        items_dict['Gold Beetle', 4],
        items_dict['Feather Leaf', 5],
        items_dict['Pike Wood', 5],
        items_dict['Bergen Ice', 5],
        items_dict['Bug Shell', 5],
        items_dict['Tough Sand', 4],
        items_dict['Vivid Water', 5],
        items_dict['Crystal Leek', 4],
        items_dict['Old Bones', 4],
        items_dict['Parched Leaves', 4],
        items_dict['White Grain', 4],
        items_dict['Curly Fern', 4],
        items_dict['Common Planter', 4],
        items_dict['Blue Mango', 4],
        items_dict['Venom Shroom', 4],
        items_dict['Green Arbor', 4],
        items_dict['Blue Grass', 4],
        items_dict['Dirty Rubble', 4],
    ],
    "Rare Consumables": [
        items_dict['Chef Sandwich', 3],
        items_dict['Mega-Sandwich', 2],
        items_dict['Sweet Berry Tea', 2],
        items_dict['Flaming Bun', 3],
        items_dict['Steak, rare', 3],
        items_dict['Chili Con Carne', 2],
        items_dict['Shrimp Risotto', 1],
        items_dict['Fruit Pie', 3],
        items_dict['Ginger Tom. Salad', 3],
    ],
    "Rare Drops": [
        items_dict['Season Apples', 5],
        items_dict['Twilight Dew', 5],
        items_dict['Rusty Bits', 5],
        items_dict['Metal Gears', 3],
        items_dict['Purple Ore Lump', 6],
        items_dict['Arid Lumber', 4],
        items_dict['Cactone Fruit', 4],
        items_dict['Palmapple Seed', 3],
        items_dict['Glaring Rock', 4],
        items_dict['Helix Relic', 5],
        items_dict['Ripe Apples', 5],
        items_dict['Sunset Dew', 5],
        items_dict['Steel Comb', 4],
        items_dict['Spiky Nut', 4],
        items_dict['Exotic Resin', 3],
        items_dict['Glowing Sphere', 4],
        items_dict['Catalop Pellet', 4],
        items_dict['Pink Petal', 3],
        items_dict['Spark Tin', 3],
    ],
    "Epic Consumables": [
        items_dict['Cross Sandwich', 2],
        items_dict['Pepper Night Tea', 1],
        items_dict['Blazing Bun', 1],
        items_dict['Chili Dog', 1],
        items_dict['Gourmet Steak', 2],
        items_dict['Cold Platter', 2],
        items_dict['Green Risotto', 2],
        items_dict['Bear Beer', 3],
        items_dict['Crab Mead', 3],
        items_dict['Whale Wine', 3],
    ],
    "Epic Drops": [
        items_dict['Bear Cicada', 3],
        items_dict['Azure Dragonfly', 3],
        items_dict['Frozen Tear', 3],
        items_dict['Winter Thorn', 2],
        items_dict['Blue Orb', 2],
        items_dict['Rainbow Gem', 3],
        items_dict['Maroon Chestnut', 4],
        items_dict['Ancient Earth', 3],
        items_dict['Lucid Shard', 3],
        items_dict['Wolf Cicada', 4],
        items_dict['Crimson Dragonfly', 3],
        items_dict['Elder Wood', 3],
        items_dict['Royal Hive', 2],
        items_dict['Moon Fruit', 3],
        items_dict['Star Fruit', 2],
        items_dict['Virus Root', 2],
        items_dict['Steel Bamboo', 4],
        items_dict['Mystery Grape', 3],
        items_dict['Cobalt Crystal', 4],
    ],
    "Legendary Consumables": [
        items_dict['Final Dinner', 1],
        items_dict['Full Course', 1],
        items_dict['One Up', 1],
        items_dict['Rising Super Star', 1],
        items_dict['Guacamole Toast', 1],
        items_dict['Cheese Spaetzle', 1],
        items_dict['Spicy Beat-0-Type', 1],
        items_dict['Durian', 1],
        items_dict['Dk Pepper', 1],
        items_dict['Mooncake', 1],
    ],
    "Pets": [
        items_dict['Orange Twister', 1],
        items_dict['Baby Peng', 1],
        items_dict['FDNI Fox', 1],
        items_dict['Good Boy', 1],
        items_dict['S-Rex', 1],
        items_dict["Lil' Reap", 1],
        items_dict['Red Liz', 1],
        items_dict['Shy Fly', 1],
        items_dict['T.A.N.K.', 1],
        items_dict['Micro Crawler', 1],
        items_dict['Cool Bar', 1],
        items_dict['Batboy', 1],
        items_dict['Butterfliege', 1],
        items_dict['Piggybank', 1],
        items_dict['Seedling', 1],
        items_dict['Turbo', 1],
        items_dict['I Rob-0T', 1],
        items_dict['Baby of the East', 1],
        items_dict['Goose', 1],
        items_dict['Nuclear Roach', 1],
        items_dict['Chunky', 1],
    ],
    "Arms": [
        items_dict["Edge o' All", 1],
        items_dict['Bronze Edge', 1],
        items_dict['Core Drill', 1],
        items_dict['Iron Edge', 1],
        items_dict['Steel Edge', 1],
        items_dict['Giga Spiral Drill', 1],
        items_dict['Silver Edge', 1],
        items_dict['Titan Edge', 1],
        items_dict['Cobalt Edge', 1],
        items_dict['Galaxy Spiral Drill', 1],
        items_dict['Laser Edge', 1],
        items_dict['Infinity Spiral Drill', 1],
        items_dict['Daikon', 1],
        items_dict['Battered Fist', 1],
        items_dict['Disciple Gloves', 1],
        items_dict['Rapier Carrot', 1],
        items_dict['Western Starfist', 1],
        items_dict['Adept Gloves', 1],
        items_dict['Aehre', 1],
        items_dict["Lawkeeper's Fist", 1],
        items_dict['Panzer Fist', 1],
        items_dict['Unbreaking Fist', 1],
        items_dict['Brostick of Force', 1],
        items_dict['Eternal Salami', 1],
        items_dict['Meister Gloves', 1],
        items_dict["Mugger's Blade", 1],
        items_dict['Hardwood Stave', 1],
        items_dict['Winterclaw', 1],
        items_dict['Maverick Edge', 1],
        items_dict['Humming Razor', 1],
        items_dict['Sunset Claw', 1],
        items_dict['Twitching Slicer', 1],
        items_dict["Survivor's Blade", 1],
        items_dict['Shuddering Cleaver', 1],
        items_dict['Hydra Fang', 1],
        items_dict['Skirmisher', 1],
        items_dict['Civilian Trigger', 1],
        items_dict['Copper Gull', 1],
        items_dict["Gunner's Trigger", 1],
        items_dict["Hunter's Bolt", 1],
        items_dict['Rough Branch', 1],
        items_dict['Silver Hawk', 1],
        items_dict['Golden Revolver', 1],
        items_dict['Bigger Stick', 1],
        items_dict['Marksmen Trigger', 1],
        items_dict['Golden Falcon', 1],
        items_dict['Knocking One', 1],
        items_dict['Pendulum Striker', 1],
        items_dict['Swiftspike', 1],
        items_dict['Climbing Pick', 1],
        items_dict['Rocksplitter', 1],
        items_dict['Prickly Bracer', 1],
        items_dict['Hidden Blade', 1],
        items_dict['Bright Bracer', 1],
        items_dict['Sneaky Shiv', 1],
        items_dict['Sparkling Bracer', 1],
        items_dict['Sonic Spike', 1],
        items_dict['Shining Bracer', 1],
        items_dict['Warkeeper', 1],
        items_dict['Mantis Whip', 1],
        items_dict['Radiant Bracer', 1],
        items_dict['Progressive All-Purpose Arms', 1],
        items_dict['Progressive Defensive Arms', 1],
        items_dict['Progressive Melee Arms', 1],
        items_dict['Progressive Ranged Arms', 1],
        items_dict['Progressive Special Arms', 1],
        items_dict['Progressive Class-Based Arms', 1],
        items_dict['Progressive Arms', 1],
    ],
    "Torsos": [
        items_dict['Second Hide', 1],
        items_dict['Bronze Mail', 1],
        items_dict['Iron Mail', 1],
        items_dict['Bronze Chest Plate', 1],
        items_dict['Steel Mail', 1],
        items_dict['Silver Chest Plate', 1],
        items_dict['Silver Mail', 1],
        items_dict['Titan Mail', 1],
        items_dict['Cobalt Mail', 1],
        items_dict['Golden Chest Plate', 1],
        items_dict['Laser Mail', 1],
        items_dict['Plate of Chests', 1],
        items_dict['Scrappy Plate', 1],
        items_dict['Spiky Jacket', 1],
        items_dict['Hardrock Plate', 1],
        items_dict['Magic Robe', 1],
        items_dict['Crystal Plate', 1],
        items_dict['Ramming Shell', 1],
        items_dict['Vermillion Mantle', 1],
        items_dict['Survival Plate', 1],
        items_dict['Timeworn Belt', 1],
        items_dict['Plated Plate', 1],
        items_dict['Reactive Plate', 1],
        items_dict['Leaf Cape', 1],
        items_dict['Bubblebelt', 1],
        items_dict['Tattered Satchel', 1],
        items_dict['Petal Cloak', 1],
        items_dict['Prism Pouch', 1],
        items_dict['Rootweave', 1],
        items_dict['Bluefiber Robe', 1],
        items_dict['Infinite Bag', 1],
        items_dict['Pioneer Vest', 1],
        items_dict['Infinity+1 Bag', 1],
        items_dict['Lifefiber Uniform', 1],
        items_dict['Bovine Armor', 1],
        items_dict['Assault Vest', 1],
        items_dict['Dessert Vest', 1],
        items_dict['Assassin Garb', 1],
        items_dict['Loose Trenchcoat', 1],
        items_dict['Shadowy Cloak', 1],
        items_dict['Centaur Vest', 1],
        items_dict['Zealous Lamellar', 1],
        items_dict['Assault Harness', 1],
        items_dict['Killing Dress', 1],
        items_dict['Progressive All-Purpose Torsos', 1],
        items_dict['Progressive Defensive Torsos', 1],
        items_dict['Progressive Mixed Torsos', 1],
        items_dict['Progressive Offensive Torsos', 1],
        items_dict['Progressive Torsos', 1],
        items_dict['Progressive Class-Based Torsos', 1],
    ],
    "Legs": [
        items_dict['Grasswalkers', 1],
        items_dict['Bronze Boots', 1],
        items_dict['Iron Boots', 1],
        items_dict['Steel Boots', 1],
        items_dict['Silver Boots', 1],
        items_dict['Titan Boots', 1],
        items_dict['Urban Sneakers', 1],
        items_dict['Cobalt Boots', 1],
        items_dict['Lead Boots', 1],
        items_dict['Laser Boots', 1],
        items_dict['Unicorn Greaves', 1],
        items_dict['Old Geta', 1],
        items_dict['Rusty Anchors', 1],
        items_dict['Bull Stompers', 1],
        items_dict['Icewalkers', 1],
        items_dict['Wooly Socks', 1],
        items_dict['Ancient Sandals', 1],
        items_dict['Curly Slippers', 1],
        items_dict['Lavish Anchors', 1],
        items_dict['Stable Footguard', 1],
        items_dict['Pathfinders', 1],
        items_dict['Hydraulic Anchors', 1],
        items_dict['Bamboots', 1],
        items_dict['Brave Anchors', 1],
        items_dict['Praetorian Anchors', 1],
        items_dict['Mistwalkers', 1],
        items_dict['Paedalos', 1],
        items_dict['Fleety Sandals', 1],
        items_dict['Feline Paws', 1],
        items_dict['Desert Sandals', 1],
        items_dict['Weird Skates', 1],
        items_dict['Carpet Runners', 1],
        items_dict['Shinkickers', 1],
        items_dict['Boom Walkers', 1],
        items_dict['Trench Boots', 1],
        items_dict['Lunatic Paws', 1],
        items_dict['Deadly Dancers', 1],
        items_dict['Combat Skates', 1],
        items_dict['Artillery Boots', 1],
        items_dict['Progressive All-Purpose Legs', 1],
        items_dict['Progressive Defensive Legs', 1],
        items_dict['Progressive Offensive Legs', 1],
        items_dict['Progressive Legs', 1],
    ],
    "Heads": [
        items_dict["Explorer's Cap", 1],
        items_dict['Bronze Goggles', 1],
        items_dict['Iron Goggles', 1],
        items_dict["Thief's Band", 1],
        items_dict['Mighty Strand', 1],
        items_dict['Strawhat', 1],
        items_dict['Steel Goggles', 1],
        items_dict['Silver Goggles', 1],
        items_dict['Dried Grass Hat', 1],
        items_dict['Titan Goggles', 1],
        items_dict['Scarecrown', 1],
        items_dict['Strawberry Hat', 1],
        items_dict["Bandit's Scarf", 1],
        items_dict['Cobalt Goggles', 1],
        items_dict['Tengu Mask', 1],
        items_dict["Burglar's Rope", 1],
        items_dict['Laser Goggles', 1],
        items_dict['The Last Strawhat', 1],
        items_dict['Gorgon Veil', 1],
        items_dict['Cooling Veil', 1],
        items_dict["Student's Bandana", 1],
        items_dict['Furry Cap', 1],
        items_dict['Proper Tophat', 1],
        items_dict["Miner's Helmet", 1],
        items_dict['Chilling Veil', 1],
        items_dict['Dented Crown', 1],
        items_dict['Red Bandana', 1],
        items_dict["Electrician's Cap", 1],
        items_dict['Climate Cowl', 1],
        items_dict['Hardhead Hat', 1],
        items_dict['Serene Bubble', 1],
        items_dict["Dragon's Bandana", 1],
        items_dict['Tranquil Earmuffs', 1],
        items_dict["Recruit's Scope", 1],
        items_dict['Shady Monocle', 1],
        items_dict['Edgy Headphones', 1],
        items_dict['Longears', 1],
        items_dict['Fin Cap', 1],
        items_dict['Nomadic Turban', 1],
        items_dict['Shiny Glasses', 1],
        items_dict['Nifty Grey Shades', 1],
        items_dict['Faedora', 1],
        items_dict['Mystic Mohawk', 1],
        items_dict['Scouting Visor', 1],
        items_dict['Furious Hothead', 1],
        items_dict['Trackwalker Visor', 1],
        items_dict['Progressive All-Purpose Heads', 1],
        items_dict['Progressive Defensive Heads', 1],
        items_dict['Progressive Offensive Heads', 1],
        items_dict['Progressive Heads', 1],
    ],
    "Dungeon Keys": [
        items_dict['Mine Key', 1],
        items_dict['Mine Master Key', 1],
        items_dict["Faj'ro Key", 1],
        items_dict["Faj'ro Master Key", 1],
        items_dict["So'najiz Key", 1],
        items_dict["Zir'vitar Key", 1],
        items_dict["Krys'kajo Key", 1],
        items_dict['Kajo Master Key', 1],
        items_dict["Ku'lero Key", 1],
        items_dict["Ku'lero Master Key", 1],
    ],
    "Chest Keys": [
        items_dict["Thief's Key", 1],
        items_dict['White Key', 1],
        items_dict['Radiant Key', 1],
    ],
    "Elements": [
        items_dict['Heat', 1],
        items_dict['Cold', 1],
        items_dict['Shock', 1],
        items_dict['Wave', 1],
    ],
    
}