# WARNING: THIS FILE HAS BEEN GENERATED!
# Modifications to this file will not be kept.
# If you need to change something here, check out codegen.py and the templates directory.


from .items import items_dict
from .types.items import ItemPoolEntry
from .types.locations import AccessInfo, LocationData
from .types.shops import ShopData
from .types.condition import *
from .locations import locations_dict

shop_dict: dict[str, ShopData] = {
    'Harbor Items': ShopData(internal_name='rookieHarborItems', name='Harbor Items', metadata={'shop': True}, access=AccessInfo(region={'linear': '2', 'open': 'open2'}, cond=[VariableCondition(name='canGrind')])),
    'Harbor Items + Blue Ice': ShopData(internal_name='rookieHarborItems', name='Harbor Items + Blue Ice', metadata={'shop': True}, access=AccessInfo(region={'linear': '2', 'open': 'open2'}, cond=[VariableCondition(name='canGrind'), ItemCondition(item_name='Blue Ice Shade', amount=1)])),
    'Harbor Items + Red Flame': ShopData(internal_name='rookieHarborItems', name='Harbor Items + Red Flame', metadata={'shop': True}, access=AccessInfo(region={'linear': '2', 'open': 'open2'}, cond=[VariableCondition(name='canGrind'), ItemCondition(item_name='Red Flame Shade', amount=1)])),
    'Harbor Items + Green Seed': ShopData(internal_name='rookieHarborItems', name='Harbor Items + Green Seed', metadata={'shop': True}, access=AccessInfo(region={'linear': '2', 'open': 'open2'}, cond=[VariableCondition(name='canGrind'), ItemCondition(item_name='Green Seed Shade', amount=1)])),
    'Harbor Weapons': ShopData(internal_name='rookieHarborWeapons', name='Harbor Weapons', metadata={'shop': True}, access=AccessInfo(region={'linear': '2', 'open': 'open2'}, cond=[VariableCondition(name='canGrind')])),
    'Harbor Weapons + Red Flame': ShopData(internal_name='rookieHarborWeapons', name='Harbor Weapons + Red Flame', metadata={'shop': True}, access=AccessInfo(region={'linear': '2', 'open': 'open2'}, cond=[VariableCondition(name='canGrind'), ItemCondition(item_name='Red Flame Shade', amount=1)])),
    'Harbor North Weapons': ShopData(internal_name='rookieHarborWeaponsNorth', name='Harbor North Weapons', metadata={'shop': True}, access=AccessInfo(region={'linear': '19', 'open': 'open8'})),
    "Tara's Shop": ShopData(internal_name='rookieHarborTara', name="Tara's Shop", metadata={'shop': True}, access=AccessInfo(region={'linear': '2', 'open': 'open2'}, cond=[VariableCondition(name='canGrind')])),
    'Harbor Backer Items': ShopData(internal_name='rookieBacker', name='Harbor Backer Items', metadata={'shop': True}, access=AccessInfo(region={'linear': '19', 'open': 'open8'})),
    'Bergen Items': ShopData(internal_name='bergenVillageItems', name='Bergen Items', metadata={'shop': True}, access=AccessInfo(region={'linear': '3', 'open': 'open3'})),
    'Bergen Items + Blue Ice': ShopData(internal_name='bergenVillageItems', name='Bergen Items + Blue Ice', metadata={'shop': True}, access=AccessInfo(region={'linear': '3', 'open': 'open3'}, cond=[ItemCondition(item_name='Blue Ice Shade', amount=1)])),
    'Bergen Items + Red Flame': ShopData(internal_name='bergenVillageItems', name='Bergen Items + Red Flame', metadata={'shop': True}, access=AccessInfo(region={'linear': '3', 'open': 'open3'}, cond=[ItemCondition(item_name='Red Flame Shade', amount=1)])),
    'Bergen Items + Green Seed': ShopData(internal_name='bergenVillageItems', name='Bergen Items + Green Seed', metadata={'shop': True}, access=AccessInfo(region={'linear': '3', 'open': 'open3'}, cond=[ItemCondition(item_name='Green Seed Shade', amount=1)])),
    'Bergen Weapons': ShopData(internal_name='bergenVillageWeapons', name='Bergen Weapons', metadata={'shop': True}, access=AccessInfo(region={'linear': '3', 'open': 'open3'})),
    "Hermit's Hut": ShopData(internal_name='bergenHermit', name="Hermit's Hut", metadata={'shop': True}, access=AccessInfo(region={'linear': '3', 'open': 'open3'})),
    "Ba'kii Items": ShopData(internal_name='bakiItems', name="Ba'kii Items", metadata={'shop': True}, access=AccessInfo(region={'linear': '11', 'open': 'open5'})),
    "Ba'kii Items + Blue Ice": ShopData(internal_name='bakiItems', name="Ba'kii Items + Blue Ice", metadata={'shop': True}, access=AccessInfo(region={'linear': '11', 'open': 'open5'}, cond=[ItemCondition(item_name='Blue Ice Shade', amount=1)])),
    "Ba'kii Items + Green Seed": ShopData(internal_name='bakiItems', name="Ba'kii Items + Green Seed", metadata={'shop': True}, access=AccessInfo(region={'linear': '11', 'open': 'open5'}, cond=[ItemCondition(item_name='Green Seed Shade', amount=1)])),
    "Ba'kii Weapons": ShopData(internal_name='bakiWeapons', name="Ba'kii Weapons", metadata={'shop': True}, access=AccessInfo(region={'linear': '11', 'open': 'open5'})),
    'Basin Vending Machine': ShopData(internal_name='basinVendingMachines', name='Basin Vending Machine', metadata={'shop': True}, access=AccessInfo(region={'linear': '23', 'open': 'open10'})),
    'Basin Items': ShopData(internal_name='basinItems', name='Basin Items', metadata={'shop': True}, access=AccessInfo(region={'linear': '23', 'open': 'open10'})),
    'Basin Weapons': ShopData(internal_name='basinWeapons', name='Basin Weapons', metadata={'shop': True}, access=AccessInfo(region={'linear': '23', 'open': 'open10'})),
    'Calzone Shop': ShopData(internal_name='basinMushroom', name='Calzone Shop', metadata={'shop': True}, access=AccessInfo(region={'linear': '23', 'open': 'open10'}, cond=[ItemCondition(item_name='Pond Slums Pass', amount=1)])),
    'Ridge Weapons': ShopData(internal_name='sapphireWeapons', name='Ridge Weapons', metadata={'shop': True}, access=AccessInfo(region={'linear': '31', 'open': 'open16'})),
    'Ridge Items': ShopData(internal_name='sapphireItems', name='Ridge Items', metadata={'shop': True}, access=AccessInfo(region={'linear': '31', 'open': 'open16'})),
    'Rhombus Weapons': ShopData(internal_name='rhombusWeapons1', name='Rhombus Weapons', metadata={'shop': True}, access=AccessInfo(region={'linear': '33', 'open': 'open20'}, cond=[VariableCondition(name='canGrind')])),
    'Rhombus Items': ShopData(internal_name='rhombusItems1', name='Rhombus Items', metadata={'shop': True}, access=AccessInfo(region={'linear': '33', 'open': 'open20'}, cond=[VariableCondition(name='canGrind')])),
    'Rhombus Curios': ShopData(internal_name='rhombusCurios', name='Rhombus Curios', metadata={'shop': True}, access=AccessInfo(region={'linear': '33', 'open': 'open20'}, cond=[VariableCondition(name='canGrind')])),
    'Rhombus Backer Items': ShopData(internal_name='rhombusBacker', name='Rhombus Backer Items', metadata={'shop': True}, access=AccessInfo(region={'linear': '33', 'open': 'open20'}, cond=[VariableCondition(name='canGrind')])),
    'Vermillion Weapons': ShopData(internal_name='aridWeapons', name='Vermillion Weapons', metadata={'shop': True}, access=AccessInfo(region={'linear': '22', 'open': 'open18'})),
    'Vermillion Items': ShopData(internal_name='aridItems', name='Vermillion Items', metadata={'shop': True}, access=AccessInfo(region={'linear': '22', 'open': 'open18'})),
    'Homestedt Items': ShopData(internal_name='homestedtItems', name='Homestedt Items', metadata={'dlc': True, 'shop': True}, access=AccessInfo(region={'open': 'openDLC1'})),
    'Homestedt Weapons': ShopData(internal_name='homestedtWeapons', name='Homestedt Weapons', metadata={'dlc': True, 'shop': True}, access=AccessInfo(region={'open': 'openDLC1'})),
    'Beach Weapons': ShopData(internal_name='beachWeapons', name='Beach Weapons', metadata={'dlc': True, 'shop': True}, access=AccessInfo(region={'open': 'openDLC_Beach'})),
    "Goat Zira's Shop": ShopData(internal_name='goatShop', name="Goat Zira's Shop", metadata={'quest': True, 'dlc': True, 'shop': True}, access=AccessInfo(region={'open': 'open20'}, cond=[QuestCondition(quest_name='Wrath of Goat'), VariableCondition(name='canGrind')])),
    'Rhombus Weapons + DLC': ShopData(internal_name='rhombusWeapons1', name='Rhombus Weapons + DLC', metadata={'dlc': True, 'shop': True}, access=AccessInfo(region={'linear': '33', 'open': 'open20'}, cond=[VariableCondition(name='canGrind')])),
}

per_shop_locations: dict[str, dict[int, LocationData]] = {
    "Harbor Items": {
        1: locations_dict['Shop Slot: Sandwich (Harbor Items)'],
        27: locations_dict['Shop Slot: Hi-Sandwich (Harbor Items)'],
        2: locations_dict['Shop Slot: Green Leaf Tea (Harbor Items)'],
        366: locations_dict['Shop Slot: Just Water (Harbor Items)'],
        64: locations_dict['Shop Slot: Spicy Bun (Harbor Items)'],
        70: locations_dict['Shop Slot: Fruit Drink (Harbor Items)'],
        73: locations_dict['Shop Slot: Rice Cracker (Harbor Items)'],
        67: locations_dict['Shop Slot: Veggie Sticks (Harbor Items)'],
    },
    "Harbor Items + Blue Ice": {
        353: locations_dict['Shop Slot: Kebab Roll (Harbor Items + Blue Ice)'],
        355: locations_dict['Shop Slot: Meaty Risotto (Harbor Items + Blue Ice)'],
    },
    "Harbor Items + Red Flame": {
        110: locations_dict['Shop Slot: Bergen Ice Cream (Harbor Items + Red Flame)'],
        165: locations_dict['Shop Slot: Sweet Lemonjuice (Harbor Items + Red Flame)'],
    },
    "Harbor Items + Green Seed": {
        290: locations_dict['Shop Slot: Salted Peanuts (Harbor Items + Green Seed)'],
        291: locations_dict["Shop Slot: Cup o' Coffee (Harbor Items + Green Seed)"],
        331: locations_dict['Shop Slot: Snack Mix (Harbor Items + Green Seed)'],
    },
    "Harbor Weapons": {
        31: locations_dict['Shop Slot: Bronze Goggles (Harbor Weapons)'],
        29: locations_dict['Shop Slot: Bronze Edge (Harbor Weapons)'],
        30: locations_dict['Shop Slot: Bronze Mail (Harbor Weapons)'],
        32: locations_dict['Shop Slot: Bronze Boots (Harbor Weapons)'],
        118: locations_dict['Shop Slot: Iron Goggles (Harbor Weapons)'],
        113: locations_dict['Shop Slot: Iron Edge (Harbor Weapons)'],
        122: locations_dict['Shop Slot: Iron Mail (Harbor Weapons)'],
        121: locations_dict['Shop Slot: Iron Boots (Harbor Weapons)'],
    },
    "Harbor Weapons + Red Flame": {
        264: locations_dict['Shop Slot: Silver Goggles (Harbor Weapons + Red Flame)'],
        266: locations_dict['Shop Slot: Silver Edge (Harbor Weapons + Red Flame)'],
        268: locations_dict['Shop Slot: Silver Mail (Harbor Weapons + Red Flame)'],
        270: locations_dict['Shop Slot: Silver Boots (Harbor Weapons + Red Flame)'],
    },
    "Harbor North Weapons": {
        204: locations_dict['Shop Slot: Steel Goggles (Harbor North Weapons)'],
        205: locations_dict['Shop Slot: Steel Edge (Harbor North Weapons)'],
        206: locations_dict['Shop Slot: Steel Mail (Harbor North Weapons)'],
        207: locations_dict['Shop Slot: Steel Boots (Harbor North Weapons)'],
        264: locations_dict['Shop Slot: Silver Goggles (Harbor North Weapons)'],
        266: locations_dict['Shop Slot: Silver Edge (Harbor North Weapons)'],
        268: locations_dict['Shop Slot: Silver Mail (Harbor North Weapons)'],
        270: locations_dict['Shop Slot: Silver Boots (Harbor North Weapons)'],
    },
    "Tara's Shop": {
        1: locations_dict["Shop Slot: Sandwich (Tara's Shop)"],
    },
    "Harbor Backer Items": {
        382: locations_dict['Shop Slot: Rising Super Star (Harbor Backer Items)'],
        490: locations_dict['Shop Slot: Dk Pepper (Harbor Backer Items)'],
        491: locations_dict['Shop Slot: Cheese Spaetzle (Harbor Backer Items)'],
        315: locations_dict['Shop Slot: Maultasche (Harbor Backer Items)'],
        493: locations_dict['Shop Slot: Durian (Harbor Backer Items)'],
        494: locations_dict['Shop Slot: PengoPop (Harbor Backer Items)'],
        495: locations_dict['Shop Slot: Spicy Beat-0-Type (Harbor Backer Items)'],
        316: locations_dict['Shop Slot: Werewolf Stick (Harbor Backer Items)'],
        516: locations_dict['Shop Slot: Mooncake (Harbor Backer Items)'],
        496: locations_dict['Shop Slot: Guacamole Toast (Harbor Backer Items)'],
        551: locations_dict['Shop Slot: Willis Waldmahl (Harbor Backer Items)'],
        637: locations_dict['Shop Slot: Pumpkin Spice Cof. (Harbor Backer Items)'],
    },
    "Bergen Items": {
        1: locations_dict['Shop Slot: Sandwich (Bergen Items)'],
        27: locations_dict['Shop Slot: Hi-Sandwich (Bergen Items)'],
        2: locations_dict['Shop Slot: Green Leaf Tea (Bergen Items)'],
        366: locations_dict['Shop Slot: Just Water (Bergen Items)'],
        64: locations_dict['Shop Slot: Spicy Bun (Bergen Items)'],
        70: locations_dict['Shop Slot: Fruit Drink (Bergen Items)'],
        73: locations_dict['Shop Slot: Rice Cracker (Bergen Items)'],
        67: locations_dict['Shop Slot: Veggie Sticks (Bergen Items)'],
    },
    "Bergen Items + Blue Ice": {
        353: locations_dict['Shop Slot: Kebab Roll (Bergen Items + Blue Ice)'],
        355: locations_dict['Shop Slot: Meaty Risotto (Bergen Items + Blue Ice)'],
    },
    "Bergen Items + Red Flame": {
        110: locations_dict['Shop Slot: Bergen Ice Cream (Bergen Items + Red Flame)'],
        165: locations_dict['Shop Slot: Sweet Lemonjuice (Bergen Items + Red Flame)'],
    },
    "Bergen Items + Green Seed": {
        290: locations_dict['Shop Slot: Salted Peanuts (Bergen Items + Green Seed)'],
        291: locations_dict["Shop Slot: Cup o' Coffee (Bergen Items + Green Seed)"],
        331: locations_dict['Shop Slot: Snack Mix (Bergen Items + Green Seed)'],
    },
    "Bergen Weapons": {
        118: locations_dict['Shop Slot: Iron Goggles (Bergen Weapons)'],
        113: locations_dict['Shop Slot: Iron Edge (Bergen Weapons)'],
        122: locations_dict['Shop Slot: Iron Mail (Bergen Weapons)'],
        121: locations_dict['Shop Slot: Iron Boots (Bergen Weapons)'],
    },
    "Hermit's Hut": {
        77: locations_dict["Shop Slot: Chili Con Carne (Hermit's Hut)"],
        165: locations_dict["Shop Slot: Sweet Lemonjuice (Hermit's Hut)"],
        3: locations_dict["Shop Slot: Sweet Berry Tea (Hermit's Hut)"],
    },
    "Ba'kii Items": {
        1: locations_dict["Shop Slot: Sandwich (Ba'kii Items)"],
        27: locations_dict["Shop Slot: Hi-Sandwich (Ba'kii Items)"],
        2: locations_dict["Shop Slot: Green Leaf Tea (Ba'kii Items)"],
        366: locations_dict["Shop Slot: Just Water (Ba'kii Items)"],
        64: locations_dict["Shop Slot: Spicy Bun (Ba'kii Items)"],
        70: locations_dict["Shop Slot: Fruit Drink (Ba'kii Items)"],
        73: locations_dict["Shop Slot: Rice Cracker (Ba'kii Items)"],
        67: locations_dict["Shop Slot: Veggie Sticks (Ba'kii Items)"],
        110: locations_dict["Shop Slot: Bergen Ice Cream (Ba'kii Items)"],
        165: locations_dict["Shop Slot: Sweet Lemonjuice (Ba'kii Items)"],
    },
    "Ba'kii Items + Blue Ice": {
        353: locations_dict["Shop Slot: Kebab Roll (Ba'kii Items + Blue Ice)"],
        355: locations_dict["Shop Slot: Meaty Risotto (Ba'kii Items + Blue Ice)"],
    },
    "Ba'kii Items + Green Seed": {
        290: locations_dict["Shop Slot: Salted Peanuts (Ba'kii Items + Green Seed)"],
        291: locations_dict["Shop Slot: Cup o' Coffee (Ba'kii Items + Green Seed)"],
        331: locations_dict["Shop Slot: Snack Mix (Ba'kii Items + Green Seed)"],
    },
    "Ba'kii Weapons": {
        118: locations_dict["Shop Slot: Iron Goggles (Ba'kii Weapons)"],
        113: locations_dict["Shop Slot: Iron Edge (Ba'kii Weapons)"],
        122: locations_dict["Shop Slot: Iron Mail (Ba'kii Weapons)"],
        121: locations_dict["Shop Slot: Iron Boots (Ba'kii Weapons)"],
        204: locations_dict["Shop Slot: Steel Goggles (Ba'kii Weapons)"],
        205: locations_dict["Shop Slot: Steel Edge (Ba'kii Weapons)"],
        206: locations_dict["Shop Slot: Steel Mail (Ba'kii Weapons)"],
        207: locations_dict["Shop Slot: Steel Boots (Ba'kii Weapons)"],
    },
    "Basin Vending Machine": {
        1: locations_dict['Shop Slot: Sandwich (Basin Vending Machine)'],
        27: locations_dict['Shop Slot: Hi-Sandwich (Basin Vending Machine)'],
        2: locations_dict['Shop Slot: Green Leaf Tea (Basin Vending Machine)'],
        366: locations_dict['Shop Slot: Just Water (Basin Vending Machine)'],
        64: locations_dict['Shop Slot: Spicy Bun (Basin Vending Machine)'],
        70: locations_dict['Shop Slot: Fruit Drink (Basin Vending Machine)'],
        73: locations_dict['Shop Slot: Rice Cracker (Basin Vending Machine)'],
        67: locations_dict['Shop Slot: Veggie Sticks (Basin Vending Machine)'],
        110: locations_dict['Shop Slot: Bergen Ice Cream (Basin Vending Machine)'],
        165: locations_dict['Shop Slot: Sweet Lemonjuice (Basin Vending Machine)'],
        290: locations_dict['Shop Slot: Salted Peanuts (Basin Vending Machine)'],
        291: locations_dict["Shop Slot: Cup o' Coffee (Basin Vending Machine)"],
        331: locations_dict['Shop Slot: Snack Mix (Basin Vending Machine)'],
        353: locations_dict['Shop Slot: Kebab Roll (Basin Vending Machine)'],
        355: locations_dict['Shop Slot: Meaty Risotto (Basin Vending Machine)'],
    },
    "Basin Items": {
        1: locations_dict['Shop Slot: Sandwich (Basin Items)'],
        27: locations_dict['Shop Slot: Hi-Sandwich (Basin Items)'],
        2: locations_dict['Shop Slot: Green Leaf Tea (Basin Items)'],
        366: locations_dict['Shop Slot: Just Water (Basin Items)'],
        353: locations_dict['Shop Slot: Kebab Roll (Basin Items)'],
        355: locations_dict['Shop Slot: Meaty Risotto (Basin Items)'],
        64: locations_dict['Shop Slot: Spicy Bun (Basin Items)'],
        70: locations_dict['Shop Slot: Fruit Drink (Basin Items)'],
        73: locations_dict['Shop Slot: Rice Cracker (Basin Items)'],
        67: locations_dict['Shop Slot: Veggie Sticks (Basin Items)'],
        110: locations_dict['Shop Slot: Bergen Ice Cream (Basin Items)'],
        165: locations_dict['Shop Slot: Sweet Lemonjuice (Basin Items)'],
        290: locations_dict['Shop Slot: Salted Peanuts (Basin Items)'],
        291: locations_dict["Shop Slot: Cup o' Coffee (Basin Items)"],
        331: locations_dict['Shop Slot: Snack Mix (Basin Items)'],
    },
    "Basin Weapons": {
        264: locations_dict['Shop Slot: Silver Goggles (Basin Weapons)'],
        266: locations_dict['Shop Slot: Silver Edge (Basin Weapons)'],
        268: locations_dict['Shop Slot: Silver Mail (Basin Weapons)'],
        270: locations_dict['Shop Slot: Silver Boots (Basin Weapons)'],
        265: locations_dict['Shop Slot: Titan Goggles (Basin Weapons)'],
        267: locations_dict['Shop Slot: Titan Edge (Basin Weapons)'],
        269: locations_dict['Shop Slot: Titan Mail (Basin Weapons)'],
        271: locations_dict['Shop Slot: Titan Boots (Basin Weapons)'],
    },
    "Calzone Shop": {
        346: locations_dict['Shop Slot: One Up (Calzone Shop)'],
    },
    "Ridge Weapons": {
        265: locations_dict['Shop Slot: Titan Goggles (Ridge Weapons)'],
        267: locations_dict['Shop Slot: Titan Edge (Ridge Weapons)'],
        269: locations_dict['Shop Slot: Titan Mail (Ridge Weapons)'],
        271: locations_dict['Shop Slot: Titan Boots (Ridge Weapons)'],
        393: locations_dict['Shop Slot: Cobalt Goggles (Ridge Weapons)'],
        394: locations_dict['Shop Slot: Cobalt Edge (Ridge Weapons)'],
        395: locations_dict['Shop Slot: Cobalt Mail (Ridge Weapons)'],
        396: locations_dict['Shop Slot: Cobalt Boots (Ridge Weapons)'],
    },
    "Ridge Items": {
        1: locations_dict['Shop Slot: Sandwich (Ridge Items)'],
        27: locations_dict['Shop Slot: Hi-Sandwich (Ridge Items)'],
        2: locations_dict['Shop Slot: Green Leaf Tea (Ridge Items)'],
        366: locations_dict['Shop Slot: Just Water (Ridge Items)'],
        353: locations_dict['Shop Slot: Kebab Roll (Ridge Items)'],
        355: locations_dict['Shop Slot: Meaty Risotto (Ridge Items)'],
        64: locations_dict['Shop Slot: Spicy Bun (Ridge Items)'],
        70: locations_dict['Shop Slot: Fruit Drink (Ridge Items)'],
        73: locations_dict['Shop Slot: Rice Cracker (Ridge Items)'],
        67: locations_dict['Shop Slot: Veggie Sticks (Ridge Items)'],
        110: locations_dict['Shop Slot: Bergen Ice Cream (Ridge Items)'],
        165: locations_dict['Shop Slot: Sweet Lemonjuice (Ridge Items)'],
        290: locations_dict['Shop Slot: Salted Peanuts (Ridge Items)'],
        291: locations_dict["Shop Slot: Cup o' Coffee (Ridge Items)"],
        331: locations_dict['Shop Slot: Snack Mix (Ridge Items)'],
    },
    "Rhombus Weapons": {
        393: locations_dict['Shop Slot: Cobalt Goggles (Rhombus Weapons)'],
        394: locations_dict['Shop Slot: Cobalt Edge (Rhombus Weapons)'],
        395: locations_dict['Shop Slot: Cobalt Mail (Rhombus Weapons)'],
        396: locations_dict['Shop Slot: Cobalt Boots (Rhombus Weapons)'],
        397: locations_dict['Shop Slot: Laser Goggles (Rhombus Weapons)'],
        398: locations_dict['Shop Slot: Laser Edge (Rhombus Weapons)'],
        399: locations_dict['Shop Slot: Laser Mail (Rhombus Weapons)'],
        400: locations_dict['Shop Slot: Laser Boots (Rhombus Weapons)'],
    },
    "Rhombus Items": {
        1: locations_dict['Shop Slot: Sandwich (Rhombus Items)'],
        27: locations_dict['Shop Slot: Hi-Sandwich (Rhombus Items)'],
        2: locations_dict['Shop Slot: Green Leaf Tea (Rhombus Items)'],
        366: locations_dict['Shop Slot: Just Water (Rhombus Items)'],
        353: locations_dict['Shop Slot: Kebab Roll (Rhombus Items)'],
        355: locations_dict['Shop Slot: Meaty Risotto (Rhombus Items)'],
        64: locations_dict['Shop Slot: Spicy Bun (Rhombus Items)'],
        70: locations_dict['Shop Slot: Fruit Drink (Rhombus Items)'],
        73: locations_dict['Shop Slot: Rice Cracker (Rhombus Items)'],
        67: locations_dict['Shop Slot: Veggie Sticks (Rhombus Items)'],
        110: locations_dict['Shop Slot: Bergen Ice Cream (Rhombus Items)'],
        165: locations_dict['Shop Slot: Sweet Lemonjuice (Rhombus Items)'],
        290: locations_dict['Shop Slot: Salted Peanuts (Rhombus Items)'],
        291: locations_dict["Shop Slot: Cup o' Coffee (Rhombus Items)"],
        331: locations_dict['Shop Slot: Snack Mix (Rhombus Items)'],
    },
    "Rhombus Curios": {
        501: locations_dict['Shop Slot: Chest Detector (Rhombus Curios)'],
    },
    "Rhombus Backer Items": {
        382: locations_dict['Shop Slot: Rising Super Star (Rhombus Backer Items)'],
        490: locations_dict['Shop Slot: Dk Pepper (Rhombus Backer Items)'],
        491: locations_dict['Shop Slot: Cheese Spaetzle (Rhombus Backer Items)'],
        315: locations_dict['Shop Slot: Maultasche (Rhombus Backer Items)'],
        493: locations_dict['Shop Slot: Durian (Rhombus Backer Items)'],
        494: locations_dict['Shop Slot: PengoPop (Rhombus Backer Items)'],
        495: locations_dict['Shop Slot: Spicy Beat-0-Type (Rhombus Backer Items)'],
        316: locations_dict['Shop Slot: Werewolf Stick (Rhombus Backer Items)'],
        516: locations_dict['Shop Slot: Mooncake (Rhombus Backer Items)'],
        496: locations_dict['Shop Slot: Guacamole Toast (Rhombus Backer Items)'],
        551: locations_dict['Shop Slot: Willis Waldmahl (Rhombus Backer Items)'],
        637: locations_dict['Shop Slot: Pumpkin Spice Cof. (Rhombus Backer Items)'],
    },
    "Vermillion Weapons": {
        204: locations_dict['Shop Slot: Steel Goggles (Vermillion Weapons)'],
        205: locations_dict['Shop Slot: Steel Edge (Vermillion Weapons)'],
        206: locations_dict['Shop Slot: Steel Mail (Vermillion Weapons)'],
        207: locations_dict['Shop Slot: Steel Boots (Vermillion Weapons)'],
        264: locations_dict['Shop Slot: Silver Goggles (Vermillion Weapons)'],
        266: locations_dict['Shop Slot: Silver Edge (Vermillion Weapons)'],
        268: locations_dict['Shop Slot: Silver Mail (Vermillion Weapons)'],
        270: locations_dict['Shop Slot: Silver Boots (Vermillion Weapons)'],
    },
    "Vermillion Items": {
        1: locations_dict['Shop Slot: Sandwich (Vermillion Items)'],
        27: locations_dict['Shop Slot: Hi-Sandwich (Vermillion Items)'],
        2: locations_dict['Shop Slot: Green Leaf Tea (Vermillion Items)'],
        366: locations_dict['Shop Slot: Just Water (Vermillion Items)'],
        64: locations_dict['Shop Slot: Spicy Bun (Vermillion Items)'],
        70: locations_dict['Shop Slot: Fruit Drink (Vermillion Items)'],
        73: locations_dict['Shop Slot: Rice Cracker (Vermillion Items)'],
        67: locations_dict['Shop Slot: Veggie Sticks (Vermillion Items)'],
    },
    "Homestedt Items": {
        1: locations_dict['Shop Slot: Sandwich (Homestedt Items)'],
        27: locations_dict['Shop Slot: Hi-Sandwich (Homestedt Items)'],
        2: locations_dict['Shop Slot: Green Leaf Tea (Homestedt Items)'],
        366: locations_dict['Shop Slot: Just Water (Homestedt Items)'],
        353: locations_dict['Shop Slot: Kebab Roll (Homestedt Items)'],
        355: locations_dict['Shop Slot: Meaty Risotto (Homestedt Items)'],
        64: locations_dict['Shop Slot: Spicy Bun (Homestedt Items)'],
        70: locations_dict['Shop Slot: Fruit Drink (Homestedt Items)'],
        73: locations_dict['Shop Slot: Rice Cracker (Homestedt Items)'],
        67: locations_dict['Shop Slot: Veggie Sticks (Homestedt Items)'],
        110: locations_dict['Shop Slot: Bergen Ice Cream (Homestedt Items)'],
        165: locations_dict['Shop Slot: Sweet Lemonjuice (Homestedt Items)'],
        291: locations_dict["Shop Slot: Cup o' Coffee (Homestedt Items)"],
        290: locations_dict['Shop Slot: Salted Peanuts (Homestedt Items)'],
        331: locations_dict['Shop Slot: Snack Mix (Homestedt Items)'],
    },
    "Homestedt Weapons": {
        397: locations_dict['Shop Slot: Laser Goggles (Homestedt Weapons)'],
        398: locations_dict['Shop Slot: Laser Edge (Homestedt Weapons)'],
        399: locations_dict['Shop Slot: Laser Mail (Homestedt Weapons)'],
        400: locations_dict['Shop Slot: Laser Boots (Homestedt Weapons)'],
    },
    "Beach Weapons": {
        568: locations_dict['Shop Slot: Cross Goggles (Beach Weapons)'],
        567: locations_dict['Shop Slot: Cross Edge (Beach Weapons)'],
        569: locations_dict['Shop Slot: Cross Mail (Beach Weapons)'],
        570: locations_dict['Shop Slot: Cross Boots (Beach Weapons)'],
    },
    "Goat Zira's Shop": {
        1: locations_dict["Shop Slot: Sandwich (Goat Zira's Shop)"],
        27: locations_dict["Shop Slot: Hi-Sandwich (Goat Zira's Shop)"],
        2: locations_dict["Shop Slot: Green Leaf Tea (Goat Zira's Shop)"],
        366: locations_dict["Shop Slot: Just Water (Goat Zira's Shop)"],
        670: locations_dict["Shop Slot: Goat Cheese (Goat Zira's Shop)"],
        671: locations_dict["Shop Slot: Goat Milk (Goat Zira's Shop)"],
    },
    "Rhombus Weapons + DLC": {
        568: locations_dict['Shop Slot: Cross Goggles (Rhombus Weapons + DLC)'],
        567: locations_dict['Shop Slot: Cross Edge (Rhombus Weapons + DLC)'],
        569: locations_dict['Shop Slot: Cross Mail (Rhombus Weapons + DLC)'],
        570: locations_dict['Shop Slot: Cross Boots (Rhombus Weapons + DLC)'],
    },
    
}

global_shop_locations: dict[int, LocationData] = {
    1: locations_dict['Global Shop Slot: Sandwich'],
    27: locations_dict['Global Shop Slot: Hi-Sandwich'],
    2: locations_dict['Global Shop Slot: Green Leaf Tea'],
    366: locations_dict['Global Shop Slot: Just Water'],
    64: locations_dict['Global Shop Slot: Spicy Bun'],
    70: locations_dict['Global Shop Slot: Fruit Drink'],
    73: locations_dict['Global Shop Slot: Rice Cracker'],
    67: locations_dict['Global Shop Slot: Veggie Sticks'],
    353: locations_dict['Global Shop Slot: Kebab Roll'],
    355: locations_dict['Global Shop Slot: Meaty Risotto'],
    110: locations_dict['Global Shop Slot: Bergen Ice Cream'],
    165: locations_dict['Global Shop Slot: Sweet Lemonjuice'],
    290: locations_dict['Global Shop Slot: Salted Peanuts'],
    291: locations_dict["Global Shop Slot: Cup o' Coffee"],
    331: locations_dict['Global Shop Slot: Snack Mix'],
    31: locations_dict['Global Shop Slot: Bronze Goggles'],
    29: locations_dict['Global Shop Slot: Bronze Edge'],
    30: locations_dict['Global Shop Slot: Bronze Mail'],
    32: locations_dict['Global Shop Slot: Bronze Boots'],
    118: locations_dict['Global Shop Slot: Iron Goggles'],
    113: locations_dict['Global Shop Slot: Iron Edge'],
    122: locations_dict['Global Shop Slot: Iron Mail'],
    121: locations_dict['Global Shop Slot: Iron Boots'],
    264: locations_dict['Global Shop Slot: Silver Goggles'],
    266: locations_dict['Global Shop Slot: Silver Edge'],
    268: locations_dict['Global Shop Slot: Silver Mail'],
    270: locations_dict['Global Shop Slot: Silver Boots'],
    204: locations_dict['Global Shop Slot: Steel Goggles'],
    205: locations_dict['Global Shop Slot: Steel Edge'],
    206: locations_dict['Global Shop Slot: Steel Mail'],
    207: locations_dict['Global Shop Slot: Steel Boots'],
    382: locations_dict['Global Shop Slot: Rising Super Star'],
    490: locations_dict['Global Shop Slot: Dk Pepper'],
    491: locations_dict['Global Shop Slot: Cheese Spaetzle'],
    315: locations_dict['Global Shop Slot: Maultasche'],
    493: locations_dict['Global Shop Slot: Durian'],
    494: locations_dict['Global Shop Slot: PengoPop'],
    495: locations_dict['Global Shop Slot: Spicy Beat-0-Type'],
    316: locations_dict['Global Shop Slot: Werewolf Stick'],
    516: locations_dict['Global Shop Slot: Mooncake'],
    496: locations_dict['Global Shop Slot: Guacamole Toast'],
    551: locations_dict['Global Shop Slot: Willis Waldmahl'],
    637: locations_dict['Global Shop Slot: Pumpkin Spice Cof.'],
    77: locations_dict['Global Shop Slot: Chili Con Carne'],
    3: locations_dict['Global Shop Slot: Sweet Berry Tea'],
    265: locations_dict['Global Shop Slot: Titan Goggles'],
    267: locations_dict['Global Shop Slot: Titan Edge'],
    269: locations_dict['Global Shop Slot: Titan Mail'],
    271: locations_dict['Global Shop Slot: Titan Boots'],
    346: locations_dict['Global Shop Slot: One Up'],
    393: locations_dict['Global Shop Slot: Cobalt Goggles'],
    394: locations_dict['Global Shop Slot: Cobalt Edge'],
    395: locations_dict['Global Shop Slot: Cobalt Mail'],
    396: locations_dict['Global Shop Slot: Cobalt Boots'],
    397: locations_dict['Global Shop Slot: Laser Goggles'],
    398: locations_dict['Global Shop Slot: Laser Edge'],
    399: locations_dict['Global Shop Slot: Laser Mail'],
    400: locations_dict['Global Shop Slot: Laser Boots'],
    501: locations_dict['Global Shop Slot: Chest Detector'],
    568: locations_dict['Global Shop Slot: Cross Goggles'],
    567: locations_dict['Global Shop Slot: Cross Edge'],
    569: locations_dict['Global Shop Slot: Cross Mail'],
    570: locations_dict['Global Shop Slot: Cross Boots'],
    670: locations_dict['Global Shop Slot: Goat Cheese'],
    671: locations_dict['Global Shop Slot: Goat Milk'],
}

shop_unlock_by_id = {
    1: ItemPoolEntry(item=items_dict['Global Slot Unlock: Sandwich', 1], quantity=1, metadata={'shop': True}),
    27: ItemPoolEntry(item=items_dict['Global Slot Unlock: Hi-Sandwich', 1], quantity=1, metadata={'shop': True}),
    2: ItemPoolEntry(item=items_dict['Global Slot Unlock: Green Leaf Tea', 1], quantity=1, metadata={'shop': True}),
    366: ItemPoolEntry(item=items_dict['Global Slot Unlock: Just Water', 1], quantity=1, metadata={'shop': True}),
    64: ItemPoolEntry(item=items_dict['Global Slot Unlock: Spicy Bun', 1], quantity=1, metadata={'shop': True}),
    70: ItemPoolEntry(item=items_dict['Global Slot Unlock: Fruit Drink', 1], quantity=1, metadata={'shop': True}),
    73: ItemPoolEntry(item=items_dict['Global Slot Unlock: Rice Cracker', 1], quantity=1, metadata={'shop': True}),
    67: ItemPoolEntry(item=items_dict['Global Slot Unlock: Veggie Sticks', 1], quantity=1, metadata={'shop': True}),
    353: ItemPoolEntry(item=items_dict['Global Slot Unlock: Kebab Roll', 1], quantity=1, metadata={'shop': True}),
    355: ItemPoolEntry(item=items_dict['Global Slot Unlock: Meaty Risotto', 1], quantity=1, metadata={'shop': True}),
    110: ItemPoolEntry(item=items_dict['Global Slot Unlock: Bergen Ice Cream', 1], quantity=1, metadata={'shop': True}),
    165: ItemPoolEntry(item=items_dict['Global Slot Unlock: Sweet Lemonjuice', 1], quantity=1, metadata={'shop': True}),
    290: ItemPoolEntry(item=items_dict['Global Slot Unlock: Salted Peanuts', 1], quantity=1, metadata={'shop': True}),
    291: ItemPoolEntry(item=items_dict["Global Slot Unlock: Cup o' Coffee", 1], quantity=1, metadata={'shop': True}),
    331: ItemPoolEntry(item=items_dict['Global Slot Unlock: Snack Mix', 1], quantity=1, metadata={'shop': True}),
    31: ItemPoolEntry(item=items_dict['Global Slot Unlock: Bronze Goggles', 1], quantity=1, metadata={'shop': True}),
    29: ItemPoolEntry(item=items_dict['Global Slot Unlock: Bronze Edge', 1], quantity=1, metadata={'shop': True}),
    30: ItemPoolEntry(item=items_dict['Global Slot Unlock: Bronze Mail', 1], quantity=1, metadata={'shop': True}),
    32: ItemPoolEntry(item=items_dict['Global Slot Unlock: Bronze Boots', 1], quantity=1, metadata={'shop': True}),
    118: ItemPoolEntry(item=items_dict['Global Slot Unlock: Iron Goggles', 1], quantity=1, metadata={'shop': True}),
    113: ItemPoolEntry(item=items_dict['Global Slot Unlock: Iron Edge', 1], quantity=1, metadata={'shop': True}),
    122: ItemPoolEntry(item=items_dict['Global Slot Unlock: Iron Mail', 1], quantity=1, metadata={'shop': True}),
    121: ItemPoolEntry(item=items_dict['Global Slot Unlock: Iron Boots', 1], quantity=1, metadata={'shop': True}),
    264: ItemPoolEntry(item=items_dict['Global Slot Unlock: Silver Goggles', 1], quantity=1, metadata={'shop': True}),
    266: ItemPoolEntry(item=items_dict['Global Slot Unlock: Silver Edge', 1], quantity=1, metadata={'shop': True}),
    268: ItemPoolEntry(item=items_dict['Global Slot Unlock: Silver Mail', 1], quantity=1, metadata={'shop': True}),
    270: ItemPoolEntry(item=items_dict['Global Slot Unlock: Silver Boots', 1], quantity=1, metadata={'shop': True}),
    204: ItemPoolEntry(item=items_dict['Global Slot Unlock: Steel Goggles', 1], quantity=1, metadata={'shop': True}),
    205: ItemPoolEntry(item=items_dict['Global Slot Unlock: Steel Edge', 1], quantity=1, metadata={'shop': True}),
    206: ItemPoolEntry(item=items_dict['Global Slot Unlock: Steel Mail', 1], quantity=1, metadata={'shop': True}),
    207: ItemPoolEntry(item=items_dict['Global Slot Unlock: Steel Boots', 1], quantity=1, metadata={'shop': True}),
    382: ItemPoolEntry(item=items_dict['Global Slot Unlock: Rising Super Star', 1], quantity=1, metadata={'shop': True}),
    490: ItemPoolEntry(item=items_dict['Global Slot Unlock: Dk Pepper', 1], quantity=1, metadata={'shop': True}),
    491: ItemPoolEntry(item=items_dict['Global Slot Unlock: Cheese Spaetzle', 1], quantity=1, metadata={'shop': True}),
    315: ItemPoolEntry(item=items_dict['Global Slot Unlock: Maultasche', 1], quantity=1, metadata={'shop': True}),
    493: ItemPoolEntry(item=items_dict['Global Slot Unlock: Durian', 1], quantity=1, metadata={'shop': True}),
    494: ItemPoolEntry(item=items_dict['Global Slot Unlock: PengoPop', 1], quantity=1, metadata={'shop': True}),
    495: ItemPoolEntry(item=items_dict['Global Slot Unlock: Spicy Beat-0-Type', 1], quantity=1, metadata={'shop': True}),
    316: ItemPoolEntry(item=items_dict['Global Slot Unlock: Werewolf Stick', 1], quantity=1, metadata={'shop': True}),
    516: ItemPoolEntry(item=items_dict['Global Slot Unlock: Mooncake', 1], quantity=1, metadata={'shop': True}),
    496: ItemPoolEntry(item=items_dict['Global Slot Unlock: Guacamole Toast', 1], quantity=1, metadata={'shop': True}),
    551: ItemPoolEntry(item=items_dict['Global Slot Unlock: Willis Waldmahl', 1], quantity=1, metadata={'shop': True}),
    637: ItemPoolEntry(item=items_dict['Global Slot Unlock: Pumpkin Spice Cof.', 1], quantity=1, metadata={'shop': True}),
    77: ItemPoolEntry(item=items_dict['Global Slot Unlock: Chili Con Carne', 1], quantity=1, metadata={'shop': True}),
    3: ItemPoolEntry(item=items_dict['Global Slot Unlock: Sweet Berry Tea', 1], quantity=1, metadata={'shop': True}),
    265: ItemPoolEntry(item=items_dict['Global Slot Unlock: Titan Goggles', 1], quantity=1, metadata={'shop': True}),
    267: ItemPoolEntry(item=items_dict['Global Slot Unlock: Titan Edge', 1], quantity=1, metadata={'shop': True}),
    269: ItemPoolEntry(item=items_dict['Global Slot Unlock: Titan Mail', 1], quantity=1, metadata={'shop': True}),
    271: ItemPoolEntry(item=items_dict['Global Slot Unlock: Titan Boots', 1], quantity=1, metadata={'shop': True}),
    346: ItemPoolEntry(item=items_dict['Global Slot Unlock: One Up', 1], quantity=1, metadata={'shop': True}),
    393: ItemPoolEntry(item=items_dict['Global Slot Unlock: Cobalt Goggles', 1], quantity=1, metadata={'shop': True}),
    394: ItemPoolEntry(item=items_dict['Global Slot Unlock: Cobalt Edge', 1], quantity=1, metadata={'shop': True}),
    395: ItemPoolEntry(item=items_dict['Global Slot Unlock: Cobalt Mail', 1], quantity=1, metadata={'shop': True}),
    396: ItemPoolEntry(item=items_dict['Global Slot Unlock: Cobalt Boots', 1], quantity=1, metadata={'shop': True}),
    397: ItemPoolEntry(item=items_dict['Global Slot Unlock: Laser Goggles', 1], quantity=1, metadata={'shop': True}),
    398: ItemPoolEntry(item=items_dict['Global Slot Unlock: Laser Edge', 1], quantity=1, metadata={'shop': True}),
    399: ItemPoolEntry(item=items_dict['Global Slot Unlock: Laser Mail', 1], quantity=1, metadata={'shop': True}),
    400: ItemPoolEntry(item=items_dict['Global Slot Unlock: Laser Boots', 1], quantity=1, metadata={'shop': True}),
    501: ItemPoolEntry(item=items_dict['Global Slot Unlock: Chest Detector', 1], quantity=1, metadata={'shop': True}),
    568: ItemPoolEntry(item=items_dict['Global Slot Unlock: Cross Goggles', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    567: ItemPoolEntry(item=items_dict['Global Slot Unlock: Cross Edge', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    569: ItemPoolEntry(item=items_dict['Global Slot Unlock: Cross Mail', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    570: ItemPoolEntry(item=items_dict['Global Slot Unlock: Cross Boots', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    670: ItemPoolEntry(item=items_dict['Global Slot Unlock: Goat Cheese', 1], quantity=1, metadata={'quest': True, 'dlc': True, 'shop': True}),
    671: ItemPoolEntry(item=items_dict['Global Slot Unlock: Goat Milk', 1], quantity=1, metadata={'quest': True, 'dlc': True, 'shop': True}),
}

shop_unlock_by_shop = {
    'rookieHarborItems': ItemPoolEntry(item=items_dict['Shop Unlock: Harbor Items', 1], quantity=1, metadata={'shop': True}),
    'rookieHarborWeapons': ItemPoolEntry(item=items_dict['Shop Unlock: Harbor Weapons', 1], quantity=1, metadata={'shop': True}),
    'rookieHarborWeaponsNorth': ItemPoolEntry(item=items_dict['Shop Unlock: Harbor North Weapons', 1], quantity=1, metadata={'shop': True}),
    'rookieHarborTara': ItemPoolEntry(item=items_dict["Shop Unlock: Tara's Shop", 1], quantity=1, metadata={'shop': True}),
    'rookieBacker': ItemPoolEntry(item=items_dict['Shop Unlock: Harbor Backer Items', 1], quantity=1, metadata={'shop': True}),
    'bergenVillageItems': ItemPoolEntry(item=items_dict['Shop Unlock: Bergen Items', 1], quantity=1, metadata={'shop': True}),
    'bergenVillageWeapons': ItemPoolEntry(item=items_dict['Shop Unlock: Bergen Weapons', 1], quantity=1, metadata={'shop': True}),
    'bergenHermit': ItemPoolEntry(item=items_dict["Shop Unlock: Hermit's Hut", 1], quantity=1, metadata={'shop': True}),
    'bakiItems': ItemPoolEntry(item=items_dict["Shop Unlock: Ba'kii Items", 1], quantity=1, metadata={'shop': True}),
    'bakiWeapons': ItemPoolEntry(item=items_dict["Shop Unlock: Ba'kii Weapons", 1], quantity=1, metadata={'shop': True}),
    'basinVendingMachines': ItemPoolEntry(item=items_dict['Shop Unlock: Basin Vending Machine', 1], quantity=1, metadata={'shop': True}),
    'basinItems': ItemPoolEntry(item=items_dict['Shop Unlock: Basin Items', 1], quantity=1, metadata={'shop': True}),
    'basinWeapons': ItemPoolEntry(item=items_dict['Shop Unlock: Basin Weapons', 1], quantity=1, metadata={'shop': True}),
    'basinMushroom': ItemPoolEntry(item=items_dict['Shop Unlock: Calzone Shop', 1], quantity=1, metadata={'shop': True}),
    'sapphireWeapons': ItemPoolEntry(item=items_dict['Shop Unlock: Ridge Weapons', 1], quantity=1, metadata={'shop': True}),
    'sapphireItems': ItemPoolEntry(item=items_dict['Shop Unlock: Ridge Items', 1], quantity=1, metadata={'shop': True}),
    'rhombusWeapons1': ItemPoolEntry(item=items_dict['Shop Unlock: Rhombus Weapons', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    'rhombusItems1': ItemPoolEntry(item=items_dict['Shop Unlock: Rhombus Items', 1], quantity=1, metadata={'shop': True}),
    'rhombusCurios': ItemPoolEntry(item=items_dict['Shop Unlock: Rhombus Curios', 1], quantity=1, metadata={'shop': True}),
    'rhombusBacker': ItemPoolEntry(item=items_dict['Shop Unlock: Rhombus Backer Items', 1], quantity=1, metadata={'shop': True}),
    'aridWeapons': ItemPoolEntry(item=items_dict['Shop Unlock: Vermillion Weapons', 1], quantity=1, metadata={'shop': True}),
    'aridItems': ItemPoolEntry(item=items_dict['Shop Unlock: Vermillion Items', 1], quantity=1, metadata={'shop': True}),
    'homestedtItems': ItemPoolEntry(item=items_dict['Shop Unlock: Homestedt Items', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    'homestedtWeapons': ItemPoolEntry(item=items_dict['Shop Unlock: Homestedt Weapons', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    'beachWeapons': ItemPoolEntry(item=items_dict['Shop Unlock: Beach Weapons', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    'goatShop': ItemPoolEntry(item=items_dict["Shop Unlock: Goat Zira's Shop", 1], quantity=1, metadata={'quest': True, 'dlc': True, 'shop': True}),
}

shop_unlock_by_shop_and_id = {
    ('rookieHarborItems', 1): ItemPoolEntry(item=items_dict['Slot Unlock: Sandwich (Harbor Items)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborItems', 27): ItemPoolEntry(item=items_dict['Slot Unlock: Hi-Sandwich (Harbor Items)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborItems', 2): ItemPoolEntry(item=items_dict['Slot Unlock: Green Leaf Tea (Harbor Items)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborItems', 366): ItemPoolEntry(item=items_dict['Slot Unlock: Just Water (Harbor Items)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborItems', 64): ItemPoolEntry(item=items_dict['Slot Unlock: Spicy Bun (Harbor Items)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborItems', 70): ItemPoolEntry(item=items_dict['Slot Unlock: Fruit Drink (Harbor Items)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborItems', 73): ItemPoolEntry(item=items_dict['Slot Unlock: Rice Cracker (Harbor Items)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborItems', 67): ItemPoolEntry(item=items_dict['Slot Unlock: Veggie Sticks (Harbor Items)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborItems', 353): ItemPoolEntry(item=items_dict['Slot Unlock: Kebab Roll (Harbor Items + Blue Ice)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborItems', 355): ItemPoolEntry(item=items_dict['Slot Unlock: Meaty Risotto (Harbor Items + Blue Ice)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborItems', 110): ItemPoolEntry(item=items_dict['Slot Unlock: Bergen Ice Cream (Harbor Items + Red Flame)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborItems', 165): ItemPoolEntry(item=items_dict['Slot Unlock: Sweet Lemonjuice (Harbor Items + Red Flame)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborItems', 290): ItemPoolEntry(item=items_dict['Slot Unlock: Salted Peanuts (Harbor Items + Green Seed)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborItems', 291): ItemPoolEntry(item=items_dict["Slot Unlock: Cup o' Coffee (Harbor Items + Green Seed)", 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborItems', 331): ItemPoolEntry(item=items_dict['Slot Unlock: Snack Mix (Harbor Items + Green Seed)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborWeapons', 31): ItemPoolEntry(item=items_dict['Slot Unlock: Bronze Goggles (Harbor Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborWeapons', 29): ItemPoolEntry(item=items_dict['Slot Unlock: Bronze Edge (Harbor Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborWeapons', 30): ItemPoolEntry(item=items_dict['Slot Unlock: Bronze Mail (Harbor Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborWeapons', 32): ItemPoolEntry(item=items_dict['Slot Unlock: Bronze Boots (Harbor Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborWeapons', 118): ItemPoolEntry(item=items_dict['Slot Unlock: Iron Goggles (Harbor Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborWeapons', 113): ItemPoolEntry(item=items_dict['Slot Unlock: Iron Edge (Harbor Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborWeapons', 122): ItemPoolEntry(item=items_dict['Slot Unlock: Iron Mail (Harbor Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborWeapons', 121): ItemPoolEntry(item=items_dict['Slot Unlock: Iron Boots (Harbor Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborWeapons', 264): ItemPoolEntry(item=items_dict['Slot Unlock: Silver Goggles (Harbor Weapons + Red Flame)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborWeapons', 266): ItemPoolEntry(item=items_dict['Slot Unlock: Silver Edge (Harbor Weapons + Red Flame)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborWeapons', 268): ItemPoolEntry(item=items_dict['Slot Unlock: Silver Mail (Harbor Weapons + Red Flame)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborWeapons', 270): ItemPoolEntry(item=items_dict['Slot Unlock: Silver Boots (Harbor Weapons + Red Flame)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborWeaponsNorth', 204): ItemPoolEntry(item=items_dict['Slot Unlock: Steel Goggles (Harbor North Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborWeaponsNorth', 205): ItemPoolEntry(item=items_dict['Slot Unlock: Steel Edge (Harbor North Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborWeaponsNorth', 206): ItemPoolEntry(item=items_dict['Slot Unlock: Steel Mail (Harbor North Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborWeaponsNorth', 207): ItemPoolEntry(item=items_dict['Slot Unlock: Steel Boots (Harbor North Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborWeaponsNorth', 264): ItemPoolEntry(item=items_dict['Slot Unlock: Silver Goggles (Harbor North Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborWeaponsNorth', 266): ItemPoolEntry(item=items_dict['Slot Unlock: Silver Edge (Harbor North Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborWeaponsNorth', 268): ItemPoolEntry(item=items_dict['Slot Unlock: Silver Mail (Harbor North Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborWeaponsNorth', 270): ItemPoolEntry(item=items_dict['Slot Unlock: Silver Boots (Harbor North Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('rookieHarborTara', 1): ItemPoolEntry(item=items_dict["Slot Unlock: Sandwich (Tara's Shop)", 1], quantity=1, metadata={'shop': True}),
    ('rookieBacker', 382): ItemPoolEntry(item=items_dict['Slot Unlock: Rising Super Star (Harbor Backer Items)', 1], quantity=1, metadata={'shop': True}),
    ('rookieBacker', 490): ItemPoolEntry(item=items_dict['Slot Unlock: Dk Pepper (Harbor Backer Items)', 1], quantity=1, metadata={'shop': True}),
    ('rookieBacker', 491): ItemPoolEntry(item=items_dict['Slot Unlock: Cheese Spaetzle (Harbor Backer Items)', 1], quantity=1, metadata={'shop': True}),
    ('rookieBacker', 315): ItemPoolEntry(item=items_dict['Slot Unlock: Maultasche (Harbor Backer Items)', 1], quantity=1, metadata={'shop': True}),
    ('rookieBacker', 493): ItemPoolEntry(item=items_dict['Slot Unlock: Durian (Harbor Backer Items)', 1], quantity=1, metadata={'shop': True}),
    ('rookieBacker', 494): ItemPoolEntry(item=items_dict['Slot Unlock: PengoPop (Harbor Backer Items)', 1], quantity=1, metadata={'shop': True}),
    ('rookieBacker', 495): ItemPoolEntry(item=items_dict['Slot Unlock: Spicy Beat-0-Type (Harbor Backer Items)', 1], quantity=1, metadata={'shop': True}),
    ('rookieBacker', 316): ItemPoolEntry(item=items_dict['Slot Unlock: Werewolf Stick (Harbor Backer Items)', 1], quantity=1, metadata={'shop': True}),
    ('rookieBacker', 516): ItemPoolEntry(item=items_dict['Slot Unlock: Mooncake (Harbor Backer Items)', 1], quantity=1, metadata={'shop': True}),
    ('rookieBacker', 496): ItemPoolEntry(item=items_dict['Slot Unlock: Guacamole Toast (Harbor Backer Items)', 1], quantity=1, metadata={'shop': True}),
    ('rookieBacker', 551): ItemPoolEntry(item=items_dict['Slot Unlock: Willis Waldmahl (Harbor Backer Items)', 1], quantity=1, metadata={'shop': True}),
    ('rookieBacker', 637): ItemPoolEntry(item=items_dict['Slot Unlock: Pumpkin Spice Cof. (Harbor Backer Items)', 1], quantity=1, metadata={'shop': True}),
    ('bergenVillageItems', 1): ItemPoolEntry(item=items_dict['Slot Unlock: Sandwich (Bergen Items)', 1], quantity=1, metadata={'shop': True}),
    ('bergenVillageItems', 27): ItemPoolEntry(item=items_dict['Slot Unlock: Hi-Sandwich (Bergen Items)', 1], quantity=1, metadata={'shop': True}),
    ('bergenVillageItems', 2): ItemPoolEntry(item=items_dict['Slot Unlock: Green Leaf Tea (Bergen Items)', 1], quantity=1, metadata={'shop': True}),
    ('bergenVillageItems', 366): ItemPoolEntry(item=items_dict['Slot Unlock: Just Water (Bergen Items)', 1], quantity=1, metadata={'shop': True}),
    ('bergenVillageItems', 64): ItemPoolEntry(item=items_dict['Slot Unlock: Spicy Bun (Bergen Items)', 1], quantity=1, metadata={'shop': True}),
    ('bergenVillageItems', 70): ItemPoolEntry(item=items_dict['Slot Unlock: Fruit Drink (Bergen Items)', 1], quantity=1, metadata={'shop': True}),
    ('bergenVillageItems', 73): ItemPoolEntry(item=items_dict['Slot Unlock: Rice Cracker (Bergen Items)', 1], quantity=1, metadata={'shop': True}),
    ('bergenVillageItems', 67): ItemPoolEntry(item=items_dict['Slot Unlock: Veggie Sticks (Bergen Items)', 1], quantity=1, metadata={'shop': True}),
    ('bergenVillageItems', 353): ItemPoolEntry(item=items_dict['Slot Unlock: Kebab Roll (Bergen Items + Blue Ice)', 1], quantity=1, metadata={'shop': True}),
    ('bergenVillageItems', 355): ItemPoolEntry(item=items_dict['Slot Unlock: Meaty Risotto (Bergen Items + Blue Ice)', 1], quantity=1, metadata={'shop': True}),
    ('bergenVillageItems', 110): ItemPoolEntry(item=items_dict['Slot Unlock: Bergen Ice Cream (Bergen Items + Red Flame)', 1], quantity=1, metadata={'shop': True}),
    ('bergenVillageItems', 165): ItemPoolEntry(item=items_dict['Slot Unlock: Sweet Lemonjuice (Bergen Items + Red Flame)', 1], quantity=1, metadata={'shop': True}),
    ('bergenVillageItems', 290): ItemPoolEntry(item=items_dict['Slot Unlock: Salted Peanuts (Bergen Items + Green Seed)', 1], quantity=1, metadata={'shop': True}),
    ('bergenVillageItems', 291): ItemPoolEntry(item=items_dict["Slot Unlock: Cup o' Coffee (Bergen Items + Green Seed)", 1], quantity=1, metadata={'shop': True}),
    ('bergenVillageItems', 331): ItemPoolEntry(item=items_dict['Slot Unlock: Snack Mix (Bergen Items + Green Seed)', 1], quantity=1, metadata={'shop': True}),
    ('bergenVillageWeapons', 118): ItemPoolEntry(item=items_dict['Slot Unlock: Iron Goggles (Bergen Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('bergenVillageWeapons', 113): ItemPoolEntry(item=items_dict['Slot Unlock: Iron Edge (Bergen Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('bergenVillageWeapons', 122): ItemPoolEntry(item=items_dict['Slot Unlock: Iron Mail (Bergen Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('bergenVillageWeapons', 121): ItemPoolEntry(item=items_dict['Slot Unlock: Iron Boots (Bergen Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('bergenHermit', 77): ItemPoolEntry(item=items_dict["Slot Unlock: Chili Con Carne (Hermit's Hut)", 1], quantity=1, metadata={'shop': True}),
    ('bergenHermit', 165): ItemPoolEntry(item=items_dict["Slot Unlock: Sweet Lemonjuice (Hermit's Hut)", 1], quantity=1, metadata={'shop': True}),
    ('bergenHermit', 3): ItemPoolEntry(item=items_dict["Slot Unlock: Sweet Berry Tea (Hermit's Hut)", 1], quantity=1, metadata={'shop': True}),
    ('bakiItems', 1): ItemPoolEntry(item=items_dict["Slot Unlock: Sandwich (Ba'kii Items)", 1], quantity=1, metadata={'shop': True}),
    ('bakiItems', 27): ItemPoolEntry(item=items_dict["Slot Unlock: Hi-Sandwich (Ba'kii Items)", 1], quantity=1, metadata={'shop': True}),
    ('bakiItems', 2): ItemPoolEntry(item=items_dict["Slot Unlock: Green Leaf Tea (Ba'kii Items)", 1], quantity=1, metadata={'shop': True}),
    ('bakiItems', 366): ItemPoolEntry(item=items_dict["Slot Unlock: Just Water (Ba'kii Items)", 1], quantity=1, metadata={'shop': True}),
    ('bakiItems', 64): ItemPoolEntry(item=items_dict["Slot Unlock: Spicy Bun (Ba'kii Items)", 1], quantity=1, metadata={'shop': True}),
    ('bakiItems', 70): ItemPoolEntry(item=items_dict["Slot Unlock: Fruit Drink (Ba'kii Items)", 1], quantity=1, metadata={'shop': True}),
    ('bakiItems', 73): ItemPoolEntry(item=items_dict["Slot Unlock: Rice Cracker (Ba'kii Items)", 1], quantity=1, metadata={'shop': True}),
    ('bakiItems', 67): ItemPoolEntry(item=items_dict["Slot Unlock: Veggie Sticks (Ba'kii Items)", 1], quantity=1, metadata={'shop': True}),
    ('bakiItems', 110): ItemPoolEntry(item=items_dict["Slot Unlock: Bergen Ice Cream (Ba'kii Items)", 1], quantity=1, metadata={'shop': True}),
    ('bakiItems', 165): ItemPoolEntry(item=items_dict["Slot Unlock: Sweet Lemonjuice (Ba'kii Items)", 1], quantity=1, metadata={'shop': True}),
    ('bakiItems', 353): ItemPoolEntry(item=items_dict["Slot Unlock: Kebab Roll (Ba'kii Items + Blue Ice)", 1], quantity=1, metadata={'shop': True}),
    ('bakiItems', 355): ItemPoolEntry(item=items_dict["Slot Unlock: Meaty Risotto (Ba'kii Items + Blue Ice)", 1], quantity=1, metadata={'shop': True}),
    ('bakiItems', 290): ItemPoolEntry(item=items_dict["Slot Unlock: Salted Peanuts (Ba'kii Items + Green Seed)", 1], quantity=1, metadata={'shop': True}),
    ('bakiItems', 291): ItemPoolEntry(item=items_dict["Slot Unlock: Cup o' Coffee (Ba'kii Items + Green Seed)", 1], quantity=1, metadata={'shop': True}),
    ('bakiItems', 331): ItemPoolEntry(item=items_dict["Slot Unlock: Snack Mix (Ba'kii Items + Green Seed)", 1], quantity=1, metadata={'shop': True}),
    ('bakiWeapons', 118): ItemPoolEntry(item=items_dict["Slot Unlock: Iron Goggles (Ba'kii Weapons)", 1], quantity=1, metadata={'shop': True}),
    ('bakiWeapons', 113): ItemPoolEntry(item=items_dict["Slot Unlock: Iron Edge (Ba'kii Weapons)", 1], quantity=1, metadata={'shop': True}),
    ('bakiWeapons', 122): ItemPoolEntry(item=items_dict["Slot Unlock: Iron Mail (Ba'kii Weapons)", 1], quantity=1, metadata={'shop': True}),
    ('bakiWeapons', 121): ItemPoolEntry(item=items_dict["Slot Unlock: Iron Boots (Ba'kii Weapons)", 1], quantity=1, metadata={'shop': True}),
    ('bakiWeapons', 204): ItemPoolEntry(item=items_dict["Slot Unlock: Steel Goggles (Ba'kii Weapons)", 1], quantity=1, metadata={'shop': True}),
    ('bakiWeapons', 205): ItemPoolEntry(item=items_dict["Slot Unlock: Steel Edge (Ba'kii Weapons)", 1], quantity=1, metadata={'shop': True}),
    ('bakiWeapons', 206): ItemPoolEntry(item=items_dict["Slot Unlock: Steel Mail (Ba'kii Weapons)", 1], quantity=1, metadata={'shop': True}),
    ('bakiWeapons', 207): ItemPoolEntry(item=items_dict["Slot Unlock: Steel Boots (Ba'kii Weapons)", 1], quantity=1, metadata={'shop': True}),
    ('basinVendingMachines', 1): ItemPoolEntry(item=items_dict['Slot Unlock: Sandwich (Basin Vending Machine)', 1], quantity=1, metadata={'shop': True}),
    ('basinVendingMachines', 27): ItemPoolEntry(item=items_dict['Slot Unlock: Hi-Sandwich (Basin Vending Machine)', 1], quantity=1, metadata={'shop': True}),
    ('basinVendingMachines', 2): ItemPoolEntry(item=items_dict['Slot Unlock: Green Leaf Tea (Basin Vending Machine)', 1], quantity=1, metadata={'shop': True}),
    ('basinVendingMachines', 366): ItemPoolEntry(item=items_dict['Slot Unlock: Just Water (Basin Vending Machine)', 1], quantity=1, metadata={'shop': True}),
    ('basinVendingMachines', 64): ItemPoolEntry(item=items_dict['Slot Unlock: Spicy Bun (Basin Vending Machine)', 1], quantity=1, metadata={'shop': True}),
    ('basinVendingMachines', 70): ItemPoolEntry(item=items_dict['Slot Unlock: Fruit Drink (Basin Vending Machine)', 1], quantity=1, metadata={'shop': True}),
    ('basinVendingMachines', 73): ItemPoolEntry(item=items_dict['Slot Unlock: Rice Cracker (Basin Vending Machine)', 1], quantity=1, metadata={'shop': True}),
    ('basinVendingMachines', 67): ItemPoolEntry(item=items_dict['Slot Unlock: Veggie Sticks (Basin Vending Machine)', 1], quantity=1, metadata={'shop': True}),
    ('basinVendingMachines', 110): ItemPoolEntry(item=items_dict['Slot Unlock: Bergen Ice Cream (Basin Vending Machine)', 1], quantity=1, metadata={'shop': True}),
    ('basinVendingMachines', 165): ItemPoolEntry(item=items_dict['Slot Unlock: Sweet Lemonjuice (Basin Vending Machine)', 1], quantity=1, metadata={'shop': True}),
    ('basinVendingMachines', 290): ItemPoolEntry(item=items_dict['Slot Unlock: Salted Peanuts (Basin Vending Machine)', 1], quantity=1, metadata={'shop': True}),
    ('basinVendingMachines', 291): ItemPoolEntry(item=items_dict["Slot Unlock: Cup o' Coffee (Basin Vending Machine)", 1], quantity=1, metadata={'shop': True}),
    ('basinVendingMachines', 331): ItemPoolEntry(item=items_dict['Slot Unlock: Snack Mix (Basin Vending Machine)', 1], quantity=1, metadata={'shop': True}),
    ('basinVendingMachines', 353): ItemPoolEntry(item=items_dict['Slot Unlock: Kebab Roll (Basin Vending Machine)', 1], quantity=1, metadata={'shop': True}),
    ('basinVendingMachines', 355): ItemPoolEntry(item=items_dict['Slot Unlock: Meaty Risotto (Basin Vending Machine)', 1], quantity=1, metadata={'shop': True}),
    ('basinItems', 1): ItemPoolEntry(item=items_dict['Slot Unlock: Sandwich (Basin Items)', 1], quantity=1, metadata={'shop': True}),
    ('basinItems', 27): ItemPoolEntry(item=items_dict['Slot Unlock: Hi-Sandwich (Basin Items)', 1], quantity=1, metadata={'shop': True}),
    ('basinItems', 2): ItemPoolEntry(item=items_dict['Slot Unlock: Green Leaf Tea (Basin Items)', 1], quantity=1, metadata={'shop': True}),
    ('basinItems', 366): ItemPoolEntry(item=items_dict['Slot Unlock: Just Water (Basin Items)', 1], quantity=1, metadata={'shop': True}),
    ('basinItems', 353): ItemPoolEntry(item=items_dict['Slot Unlock: Kebab Roll (Basin Items)', 1], quantity=1, metadata={'shop': True}),
    ('basinItems', 355): ItemPoolEntry(item=items_dict['Slot Unlock: Meaty Risotto (Basin Items)', 1], quantity=1, metadata={'shop': True}),
    ('basinItems', 64): ItemPoolEntry(item=items_dict['Slot Unlock: Spicy Bun (Basin Items)', 1], quantity=1, metadata={'shop': True}),
    ('basinItems', 70): ItemPoolEntry(item=items_dict['Slot Unlock: Fruit Drink (Basin Items)', 1], quantity=1, metadata={'shop': True}),
    ('basinItems', 73): ItemPoolEntry(item=items_dict['Slot Unlock: Rice Cracker (Basin Items)', 1], quantity=1, metadata={'shop': True}),
    ('basinItems', 67): ItemPoolEntry(item=items_dict['Slot Unlock: Veggie Sticks (Basin Items)', 1], quantity=1, metadata={'shop': True}),
    ('basinItems', 110): ItemPoolEntry(item=items_dict['Slot Unlock: Bergen Ice Cream (Basin Items)', 1], quantity=1, metadata={'shop': True}),
    ('basinItems', 165): ItemPoolEntry(item=items_dict['Slot Unlock: Sweet Lemonjuice (Basin Items)', 1], quantity=1, metadata={'shop': True}),
    ('basinItems', 290): ItemPoolEntry(item=items_dict['Slot Unlock: Salted Peanuts (Basin Items)', 1], quantity=1, metadata={'shop': True}),
    ('basinItems', 291): ItemPoolEntry(item=items_dict["Slot Unlock: Cup o' Coffee (Basin Items)", 1], quantity=1, metadata={'shop': True}),
    ('basinItems', 331): ItemPoolEntry(item=items_dict['Slot Unlock: Snack Mix (Basin Items)', 1], quantity=1, metadata={'shop': True}),
    ('basinWeapons', 264): ItemPoolEntry(item=items_dict['Slot Unlock: Silver Goggles (Basin Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('basinWeapons', 266): ItemPoolEntry(item=items_dict['Slot Unlock: Silver Edge (Basin Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('basinWeapons', 268): ItemPoolEntry(item=items_dict['Slot Unlock: Silver Mail (Basin Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('basinWeapons', 270): ItemPoolEntry(item=items_dict['Slot Unlock: Silver Boots (Basin Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('basinWeapons', 265): ItemPoolEntry(item=items_dict['Slot Unlock: Titan Goggles (Basin Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('basinWeapons', 267): ItemPoolEntry(item=items_dict['Slot Unlock: Titan Edge (Basin Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('basinWeapons', 269): ItemPoolEntry(item=items_dict['Slot Unlock: Titan Mail (Basin Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('basinWeapons', 271): ItemPoolEntry(item=items_dict['Slot Unlock: Titan Boots (Basin Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('basinMushroom', 346): ItemPoolEntry(item=items_dict['Slot Unlock: One Up (Calzone Shop)', 1], quantity=1, metadata={'shop': True}),
    ('sapphireWeapons', 265): ItemPoolEntry(item=items_dict['Slot Unlock: Titan Goggles (Ridge Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('sapphireWeapons', 267): ItemPoolEntry(item=items_dict['Slot Unlock: Titan Edge (Ridge Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('sapphireWeapons', 269): ItemPoolEntry(item=items_dict['Slot Unlock: Titan Mail (Ridge Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('sapphireWeapons', 271): ItemPoolEntry(item=items_dict['Slot Unlock: Titan Boots (Ridge Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('sapphireWeapons', 393): ItemPoolEntry(item=items_dict['Slot Unlock: Cobalt Goggles (Ridge Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('sapphireWeapons', 394): ItemPoolEntry(item=items_dict['Slot Unlock: Cobalt Edge (Ridge Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('sapphireWeapons', 395): ItemPoolEntry(item=items_dict['Slot Unlock: Cobalt Mail (Ridge Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('sapphireWeapons', 396): ItemPoolEntry(item=items_dict['Slot Unlock: Cobalt Boots (Ridge Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('sapphireItems', 1): ItemPoolEntry(item=items_dict['Slot Unlock: Sandwich (Ridge Items)', 1], quantity=1, metadata={'shop': True}),
    ('sapphireItems', 27): ItemPoolEntry(item=items_dict['Slot Unlock: Hi-Sandwich (Ridge Items)', 1], quantity=1, metadata={'shop': True}),
    ('sapphireItems', 2): ItemPoolEntry(item=items_dict['Slot Unlock: Green Leaf Tea (Ridge Items)', 1], quantity=1, metadata={'shop': True}),
    ('sapphireItems', 366): ItemPoolEntry(item=items_dict['Slot Unlock: Just Water (Ridge Items)', 1], quantity=1, metadata={'shop': True}),
    ('sapphireItems', 353): ItemPoolEntry(item=items_dict['Slot Unlock: Kebab Roll (Ridge Items)', 1], quantity=1, metadata={'shop': True}),
    ('sapphireItems', 355): ItemPoolEntry(item=items_dict['Slot Unlock: Meaty Risotto (Ridge Items)', 1], quantity=1, metadata={'shop': True}),
    ('sapphireItems', 64): ItemPoolEntry(item=items_dict['Slot Unlock: Spicy Bun (Ridge Items)', 1], quantity=1, metadata={'shop': True}),
    ('sapphireItems', 70): ItemPoolEntry(item=items_dict['Slot Unlock: Fruit Drink (Ridge Items)', 1], quantity=1, metadata={'shop': True}),
    ('sapphireItems', 73): ItemPoolEntry(item=items_dict['Slot Unlock: Rice Cracker (Ridge Items)', 1], quantity=1, metadata={'shop': True}),
    ('sapphireItems', 67): ItemPoolEntry(item=items_dict['Slot Unlock: Veggie Sticks (Ridge Items)', 1], quantity=1, metadata={'shop': True}),
    ('sapphireItems', 110): ItemPoolEntry(item=items_dict['Slot Unlock: Bergen Ice Cream (Ridge Items)', 1], quantity=1, metadata={'shop': True}),
    ('sapphireItems', 165): ItemPoolEntry(item=items_dict['Slot Unlock: Sweet Lemonjuice (Ridge Items)', 1], quantity=1, metadata={'shop': True}),
    ('sapphireItems', 290): ItemPoolEntry(item=items_dict['Slot Unlock: Salted Peanuts (Ridge Items)', 1], quantity=1, metadata={'shop': True}),
    ('sapphireItems', 291): ItemPoolEntry(item=items_dict["Slot Unlock: Cup o' Coffee (Ridge Items)", 1], quantity=1, metadata={'shop': True}),
    ('sapphireItems', 331): ItemPoolEntry(item=items_dict['Slot Unlock: Snack Mix (Ridge Items)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusWeapons1', 393): ItemPoolEntry(item=items_dict['Slot Unlock: Cobalt Goggles (Rhombus Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusWeapons1', 394): ItemPoolEntry(item=items_dict['Slot Unlock: Cobalt Edge (Rhombus Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusWeapons1', 395): ItemPoolEntry(item=items_dict['Slot Unlock: Cobalt Mail (Rhombus Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusWeapons1', 396): ItemPoolEntry(item=items_dict['Slot Unlock: Cobalt Boots (Rhombus Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusWeapons1', 397): ItemPoolEntry(item=items_dict['Slot Unlock: Laser Goggles (Rhombus Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusWeapons1', 398): ItemPoolEntry(item=items_dict['Slot Unlock: Laser Edge (Rhombus Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusWeapons1', 399): ItemPoolEntry(item=items_dict['Slot Unlock: Laser Mail (Rhombus Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusWeapons1', 400): ItemPoolEntry(item=items_dict['Slot Unlock: Laser Boots (Rhombus Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusItems1', 1): ItemPoolEntry(item=items_dict['Slot Unlock: Sandwich (Rhombus Items)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusItems1', 27): ItemPoolEntry(item=items_dict['Slot Unlock: Hi-Sandwich (Rhombus Items)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusItems1', 2): ItemPoolEntry(item=items_dict['Slot Unlock: Green Leaf Tea (Rhombus Items)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusItems1', 366): ItemPoolEntry(item=items_dict['Slot Unlock: Just Water (Rhombus Items)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusItems1', 353): ItemPoolEntry(item=items_dict['Slot Unlock: Kebab Roll (Rhombus Items)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusItems1', 355): ItemPoolEntry(item=items_dict['Slot Unlock: Meaty Risotto (Rhombus Items)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusItems1', 64): ItemPoolEntry(item=items_dict['Slot Unlock: Spicy Bun (Rhombus Items)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusItems1', 70): ItemPoolEntry(item=items_dict['Slot Unlock: Fruit Drink (Rhombus Items)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusItems1', 73): ItemPoolEntry(item=items_dict['Slot Unlock: Rice Cracker (Rhombus Items)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusItems1', 67): ItemPoolEntry(item=items_dict['Slot Unlock: Veggie Sticks (Rhombus Items)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusItems1', 110): ItemPoolEntry(item=items_dict['Slot Unlock: Bergen Ice Cream (Rhombus Items)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusItems1', 165): ItemPoolEntry(item=items_dict['Slot Unlock: Sweet Lemonjuice (Rhombus Items)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusItems1', 290): ItemPoolEntry(item=items_dict['Slot Unlock: Salted Peanuts (Rhombus Items)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusItems1', 291): ItemPoolEntry(item=items_dict["Slot Unlock: Cup o' Coffee (Rhombus Items)", 1], quantity=1, metadata={'shop': True}),
    ('rhombusItems1', 331): ItemPoolEntry(item=items_dict['Slot Unlock: Snack Mix (Rhombus Items)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusCurios', 501): ItemPoolEntry(item=items_dict['Slot Unlock: Chest Detector (Rhombus Curios)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusBacker', 382): ItemPoolEntry(item=items_dict['Slot Unlock: Rising Super Star (Rhombus Backer Items)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusBacker', 490): ItemPoolEntry(item=items_dict['Slot Unlock: Dk Pepper (Rhombus Backer Items)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusBacker', 491): ItemPoolEntry(item=items_dict['Slot Unlock: Cheese Spaetzle (Rhombus Backer Items)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusBacker', 315): ItemPoolEntry(item=items_dict['Slot Unlock: Maultasche (Rhombus Backer Items)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusBacker', 493): ItemPoolEntry(item=items_dict['Slot Unlock: Durian (Rhombus Backer Items)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusBacker', 494): ItemPoolEntry(item=items_dict['Slot Unlock: PengoPop (Rhombus Backer Items)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusBacker', 495): ItemPoolEntry(item=items_dict['Slot Unlock: Spicy Beat-0-Type (Rhombus Backer Items)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusBacker', 316): ItemPoolEntry(item=items_dict['Slot Unlock: Werewolf Stick (Rhombus Backer Items)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusBacker', 516): ItemPoolEntry(item=items_dict['Slot Unlock: Mooncake (Rhombus Backer Items)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusBacker', 496): ItemPoolEntry(item=items_dict['Slot Unlock: Guacamole Toast (Rhombus Backer Items)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusBacker', 551): ItemPoolEntry(item=items_dict['Slot Unlock: Willis Waldmahl (Rhombus Backer Items)', 1], quantity=1, metadata={'shop': True}),
    ('rhombusBacker', 637): ItemPoolEntry(item=items_dict['Slot Unlock: Pumpkin Spice Cof. (Rhombus Backer Items)', 1], quantity=1, metadata={'shop': True}),
    ('aridWeapons', 204): ItemPoolEntry(item=items_dict['Slot Unlock: Steel Goggles (Vermillion Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('aridWeapons', 205): ItemPoolEntry(item=items_dict['Slot Unlock: Steel Edge (Vermillion Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('aridWeapons', 206): ItemPoolEntry(item=items_dict['Slot Unlock: Steel Mail (Vermillion Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('aridWeapons', 207): ItemPoolEntry(item=items_dict['Slot Unlock: Steel Boots (Vermillion Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('aridWeapons', 264): ItemPoolEntry(item=items_dict['Slot Unlock: Silver Goggles (Vermillion Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('aridWeapons', 266): ItemPoolEntry(item=items_dict['Slot Unlock: Silver Edge (Vermillion Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('aridWeapons', 268): ItemPoolEntry(item=items_dict['Slot Unlock: Silver Mail (Vermillion Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('aridWeapons', 270): ItemPoolEntry(item=items_dict['Slot Unlock: Silver Boots (Vermillion Weapons)', 1], quantity=1, metadata={'shop': True}),
    ('aridItems', 1): ItemPoolEntry(item=items_dict['Slot Unlock: Sandwich (Vermillion Items)', 1], quantity=1, metadata={'shop': True}),
    ('aridItems', 27): ItemPoolEntry(item=items_dict['Slot Unlock: Hi-Sandwich (Vermillion Items)', 1], quantity=1, metadata={'shop': True}),
    ('aridItems', 2): ItemPoolEntry(item=items_dict['Slot Unlock: Green Leaf Tea (Vermillion Items)', 1], quantity=1, metadata={'shop': True}),
    ('aridItems', 366): ItemPoolEntry(item=items_dict['Slot Unlock: Just Water (Vermillion Items)', 1], quantity=1, metadata={'shop': True}),
    ('aridItems', 64): ItemPoolEntry(item=items_dict['Slot Unlock: Spicy Bun (Vermillion Items)', 1], quantity=1, metadata={'shop': True}),
    ('aridItems', 70): ItemPoolEntry(item=items_dict['Slot Unlock: Fruit Drink (Vermillion Items)', 1], quantity=1, metadata={'shop': True}),
    ('aridItems', 73): ItemPoolEntry(item=items_dict['Slot Unlock: Rice Cracker (Vermillion Items)', 1], quantity=1, metadata={'shop': True}),
    ('aridItems', 67): ItemPoolEntry(item=items_dict['Slot Unlock: Veggie Sticks (Vermillion Items)', 1], quantity=1, metadata={'shop': True}),
    ('homestedtItems', 1): ItemPoolEntry(item=items_dict['Slot Unlock: Sandwich (Homestedt Items)', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    ('homestedtItems', 27): ItemPoolEntry(item=items_dict['Slot Unlock: Hi-Sandwich (Homestedt Items)', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    ('homestedtItems', 2): ItemPoolEntry(item=items_dict['Slot Unlock: Green Leaf Tea (Homestedt Items)', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    ('homestedtItems', 366): ItemPoolEntry(item=items_dict['Slot Unlock: Just Water (Homestedt Items)', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    ('homestedtItems', 353): ItemPoolEntry(item=items_dict['Slot Unlock: Kebab Roll (Homestedt Items)', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    ('homestedtItems', 355): ItemPoolEntry(item=items_dict['Slot Unlock: Meaty Risotto (Homestedt Items)', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    ('homestedtItems', 64): ItemPoolEntry(item=items_dict['Slot Unlock: Spicy Bun (Homestedt Items)', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    ('homestedtItems', 70): ItemPoolEntry(item=items_dict['Slot Unlock: Fruit Drink (Homestedt Items)', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    ('homestedtItems', 73): ItemPoolEntry(item=items_dict['Slot Unlock: Rice Cracker (Homestedt Items)', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    ('homestedtItems', 67): ItemPoolEntry(item=items_dict['Slot Unlock: Veggie Sticks (Homestedt Items)', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    ('homestedtItems', 110): ItemPoolEntry(item=items_dict['Slot Unlock: Bergen Ice Cream (Homestedt Items)', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    ('homestedtItems', 165): ItemPoolEntry(item=items_dict['Slot Unlock: Sweet Lemonjuice (Homestedt Items)', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    ('homestedtItems', 291): ItemPoolEntry(item=items_dict["Slot Unlock: Cup o' Coffee (Homestedt Items)", 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    ('homestedtItems', 290): ItemPoolEntry(item=items_dict['Slot Unlock: Salted Peanuts (Homestedt Items)', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    ('homestedtItems', 331): ItemPoolEntry(item=items_dict['Slot Unlock: Snack Mix (Homestedt Items)', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    ('homestedtWeapons', 397): ItemPoolEntry(item=items_dict['Slot Unlock: Laser Goggles (Homestedt Weapons)', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    ('homestedtWeapons', 398): ItemPoolEntry(item=items_dict['Slot Unlock: Laser Edge (Homestedt Weapons)', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    ('homestedtWeapons', 399): ItemPoolEntry(item=items_dict['Slot Unlock: Laser Mail (Homestedt Weapons)', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    ('homestedtWeapons', 400): ItemPoolEntry(item=items_dict['Slot Unlock: Laser Boots (Homestedt Weapons)', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    ('beachWeapons', 568): ItemPoolEntry(item=items_dict['Slot Unlock: Cross Goggles (Beach Weapons)', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    ('beachWeapons', 567): ItemPoolEntry(item=items_dict['Slot Unlock: Cross Edge (Beach Weapons)', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    ('beachWeapons', 569): ItemPoolEntry(item=items_dict['Slot Unlock: Cross Mail (Beach Weapons)', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    ('beachWeapons', 570): ItemPoolEntry(item=items_dict['Slot Unlock: Cross Boots (Beach Weapons)', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    ('goatShop', 1): ItemPoolEntry(item=items_dict["Slot Unlock: Sandwich (Goat Zira's Shop)", 1], quantity=1, metadata={'quest': True, 'dlc': True, 'shop': True}),
    ('goatShop', 27): ItemPoolEntry(item=items_dict["Slot Unlock: Hi-Sandwich (Goat Zira's Shop)", 1], quantity=1, metadata={'quest': True, 'dlc': True, 'shop': True}),
    ('goatShop', 2): ItemPoolEntry(item=items_dict["Slot Unlock: Green Leaf Tea (Goat Zira's Shop)", 1], quantity=1, metadata={'quest': True, 'dlc': True, 'shop': True}),
    ('goatShop', 366): ItemPoolEntry(item=items_dict["Slot Unlock: Just Water (Goat Zira's Shop)", 1], quantity=1, metadata={'quest': True, 'dlc': True, 'shop': True}),
    ('goatShop', 670): ItemPoolEntry(item=items_dict["Slot Unlock: Goat Cheese (Goat Zira's Shop)", 1], quantity=1, metadata={'quest': True, 'dlc': True, 'shop': True}),
    ('goatShop', 671): ItemPoolEntry(item=items_dict["Slot Unlock: Goat Milk (Goat Zira's Shop)", 1], quantity=1, metadata={'quest': True, 'dlc': True, 'shop': True}),
    ('rhombusWeapons1', 568): ItemPoolEntry(item=items_dict['Slot Unlock: Cross Goggles (Rhombus Weapons + DLC)', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    ('rhombusWeapons1', 567): ItemPoolEntry(item=items_dict['Slot Unlock: Cross Edge (Rhombus Weapons + DLC)', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    ('rhombusWeapons1', 569): ItemPoolEntry(item=items_dict['Slot Unlock: Cross Mail (Rhombus Weapons + DLC)', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
    ('rhombusWeapons1', 570): ItemPoolEntry(item=items_dict['Slot Unlock: Cross Boots (Rhombus Weapons + DLC)', 1], quantity=1, metadata={'dlc': True, 'shop': True}),
}